/* XENO_FILES — the bytes behind Library items.
 *
 * Platform contract this stands in for:  GET /api/v2/library/items/:id/content  (one file)
 *                                        POST /api/v2/library/archive {ids}      (several, as one zip)
 *
 * · A file the person UPLOADED keeps its exact bytes, in IndexedDB (the browser's store for blobs — Drive's
 *   and Figma's offline caches use it; localStorage cannot hold binary and caps at ~5 MB). It survives reload.
 * · A SAMPLE file (the seeded library) has no bytes anywhere, so one is made in the file's real format — a real
 *   PNG at the stated size, a real PDF, a real WAV, a real WebM, CSV for a sheet, source text for code — and the
 *   file says inside that it is sample content. The format is never faked: when the sample cannot be the stated
 *   format (an .mp4 recorded as WebM) the downloaded name says what it really is.
 * · Several files download as ONE zip (Drive, Dropbox, Box), written here with STORE entries and CRC-32.
 */
(() => {
  const X = () => window.XW;
  // ---------- IndexedDB: uploaded bytes ----------
  let dbp = null;
  const db = () => (dbp ||= new Promise((res, rej) => { const r = indexedDB.open('xw.files', 1); r.onupgradeneeded = () => r.result.createObjectStore('blobs'); r.onsuccess = () => res(r.result); r.onerror = () => rej(r.error); }));
  const tx = async (mode, fn) => { const d = await db(); return new Promise((res, rej) => { const t = d.transaction('blobs', mode); const q = fn(t.objectStore('blobs')); t.oncomplete = () => res(q?.result); t.onerror = () => rej(t.error); }); };
  const put = (id, blob) => tx('readwrite', (s) => s.put(blob, id)).catch(() => null);
  const get = (id) => tx('readonly', (s) => s.get(id)).catch(() => null);
  const del = (id) => tx('readwrite', (s) => s.delete(id)).catch(() => null);

  // ---------- sample content, in the real format ----------
  const SAMPLE = 'Sample content — generated by the XENO workspace prototype. On the platform this downloads the stored file.';
  const ext = (n) => { const m = /\.([a-z0-9]{1,6})$/i.exec(n); return m ? m[1].toLowerCase() : ''; };
  const withExt = (n, e) => (ext(n) === e ? n : ext(n) ? n.replace(/\.[a-z0-9]{1,6}$/i, '.' + e) : `${n}.${e}`);
  const text = (s, type = 'text/plain') => new Blob([s], { type: type + ';charset=utf-8' });
  const canvasBlob = (c, type) => new Promise((r) => c.toBlob(r, type));
  function paint(c, f) {
    const g = c.getContext('2d'), W = c.width, H = c.height;
    const gr = g.createLinearGradient(0, 0, W, H); gr.addColorStop(0, '#1b1b1f'); gr.addColorStop(1, '#3a3a42'); g.fillStyle = gr; g.fillRect(0, 0, W, H);
    g.fillStyle = 'rgba(255,255,255,.06)'; for (let i = 0; i < 6; i++) g.fillRect(W * (0.08 + i * 0.15), H * 0.62, W * 0.11, H * 0.22);
    g.fillStyle = '#f4f4f4'; g.font = `600 ${Math.round(H / 14)}px Inter, system-ui, sans-serif`; g.fillText(f.name, W * 0.07, H * 0.3);
    g.fillStyle = 'rgba(244,244,244,.55)'; g.font = `${Math.round(H / 34)}px Inter, system-ui, sans-serif`; g.fillText(SAMPLE, W * 0.07, H * 0.38);
  }
  async function png(f) { const m = f.media || { width: 1600, height: 1000 }, k = Math.min(1, 4096 / Math.max(m.width, m.height)); const c = document.createElement('canvas'); c.width = Math.round(m.width * k); c.height = Math.round(m.height * k); paint(c, f); return canvasBlob(c, 'image/png'); }
  async function webm(f) {
    const c = document.createElement('canvas'); c.width = 640; c.height = 360; paint(c, f);
    if (!window.MediaRecorder || !c.captureStream) return null;
    const rec = new MediaRecorder(c.captureStream(30), { mimeType: MediaRecorder.isTypeSupported('video/webm;codecs=vp9') ? 'video/webm;codecs=vp9' : 'video/webm' });
    const parts = []; rec.ondataavailable = (e) => e.data.size && parts.push(e.data);
    const done = new Promise((r) => { rec.onstop = r; }); rec.start(); const g = c.getContext('2d'); let t = 0;
    const id = setInterval(() => { paint(c, f); g.fillStyle = '#f4f4f4'; g.fillRect((t++ * 12) % c.width, c.height - 8, 40, 4); }, 33);
    await new Promise((r) => setTimeout(r, 1500)); clearInterval(id); rec.stop(); await done; return new Blob(parts, { type: 'video/webm' });
  }
  function wav(seconds = 2, hz = 440) {
    const rate = 22050, n = rate * seconds, buf = new ArrayBuffer(44 + n * 2), v = new DataView(buf); const w = (o, s) => [...s].forEach((ch, i) => v.setUint8(o + i, ch.charCodeAt(0)));
    w(0, 'RIFF'); v.setUint32(4, 36 + n * 2, true); w(8, 'WAVE'); w(12, 'fmt '); v.setUint32(16, 16, true); v.setUint16(20, 1, true); v.setUint16(22, 1, true); v.setUint32(24, rate, true); v.setUint32(28, rate * 2, true); v.setUint16(32, 2, true); v.setUint16(34, 16, true); w(36, 'data'); v.setUint32(40, n * 2, true);
    for (let i = 0; i < n; i++) { const env = Math.min(1, i / 2000, (n - i) / 2000); v.setInt16(44 + i * 2, Math.sin((2 * Math.PI * hz * i) / rate) * 0.25 * env * 32767, true); }
    return new Blob([buf], { type: 'audio/wav' });
  }
  function pdf(title, lines) {
    const esc = (s) => s.replace(/[\\()]/g, (c) => '\\' + c).replace(/[^\x20-\x7e]/g, '-');
    const content = ['BT /F1 22 Tf 72 760 Td (' + esc(title) + ') Tj ET', ...lines.map((l, i) => `BT /F1 11 Tf 72 ${724 - i * 18} Td (${esc(l)}) Tj ET`)].join('\n');
    const objs = ['<< /Type /Catalog /Pages 2 0 R >>', '<< /Type /Pages /Kids [3 0 R] /Count 1 >>', '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>', `<< /Length ${content.length} >>\nstream\n${content}\nendstream`, '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];
    let out = '%PDF-1.4\n'; const offs = []; objs.forEach((o, i) => { offs.push(out.length); out += `${i + 1} 0 obj\n${o}\nendobj\n`; });
    const x = out.length; out += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n${offs.map((o) => String(o).padStart(10, '0') + ' 00000 n \n').join('')}trailer\n<< /Size ${objs.length + 1} /Root 1 0 R >>\nstartxref\n${x}\n%%EOF\n`;
    return new Blob([out], { type: 'application/pdf' });
  }
  const meta = (f) => [`Made in ${X()?.PR?.[f.source.product]?.name || f.source.product}`, f.project ? `Project: ${f.project}` : null, f.source.chat ? `From chat: ${f.source.chat}` : null, `Updated ${new Date(f.updatedAt).toLocaleString('en-GB')}`].filter(Boolean);
  async function sample(f) {
    const e = ext(f.name);
    if (f.kind === 'image' || ['png', 'jpg', 'jpeg', 'webp'].includes(e)) return { blob: await png(f), name: withExt(f.name, 'png') };
    if (f.kind === 'video') { const b = await webm(f); return b ? { blob: b, name: withExt(f.name, 'webm') } : { blob: text(`${f.name}\n\n${SAMPLE}\n`), name: withExt(f.name, 'txt') }; }
    if (f.kind === 'audio') return { blob: wav(), name: withExt(f.name, 'wav') };
    if (e === 'pdf') return { blob: pdf(f.name.replace(/\.pdf$/i, ''), [...meta(f), '', SAMPLE]), name: f.name };
    if (f.kind === 'sheet') return { blob: text(`Item,Owner,Amount\nDesign,Mira,1200\nBuild,Kit,3400\nLaunch,Emilian,800\n\n"${SAMPLE}"\n`, 'text/csv'), name: withExt(f.name, 'csv') };
    if (e === 'json' || e === 'xflow') return { blob: text(JSON.stringify({ name: f.name, note: SAMPLE, ...(e === 'xflow' ? { nodes: [{ id: 'trigger', type: 'schedule', every: '1d' }, { id: 'sync', type: 'http' }], edges: [['trigger', 'sync']] } : { tokens: { 'color.text': '#f4f4f4', 'color.canvas': '#0a0a0a' } }) }, null, 2), 'application/json'), name: f.name };
    if (e === 'diff') return { blob: text(`# ${SAMPLE}\n--- a/src/auth/gate.ts\n+++ b/src/auth/gate.ts\n@@ -1,3 +1,3 @@\n-export const gate = legacyGate;\n+export const gate = verifiedGate;\n`), name: f.name };
    if (e === 'ts' || e === 'js') return { blob: text(`// ${SAMPLE}\nimport { test, expect } from 'vitest';\n\ntest('${f.name}', () => {\n  expect(true).toBe(true);\n});\n`), name: f.name };
    const body = `# ${f.name.replace(/\.md$/i, '')}\n\n${meta(f).map((l) => `- ${l}`).join('\n')}\n\n> ${SAMPLE}\n`;
    return { blob: text(body, 'text/markdown'), name: withExt(f.name, 'md') };
  }
  async function bytesFor(f) { const b = await get(f.id); return b ? { blob: b, name: f.name, real: true } : { ...(await sample(f)), real: false }; }

  // ---------- zip (STORE) ----------
  const CRC = (() => { const t = new Uint32Array(256); for (let n = 0; n < 256; n++) { let c = n; for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1; t[n] = c >>> 0; } return t; })();
  const crc32 = (u8) => { let c = 0xffffffff; for (let i = 0; i < u8.length; i++) c = CRC[(c ^ u8[i]) & 0xff] ^ (c >>> 8); return (c ^ 0xffffffff) >>> 0; };
  async function zip(entries) {
    const enc = new TextEncoder(), parts = [], central = []; let off = 0; const seen = new Map();
    const d = new Date(), dosT = (d.getHours() << 11) | (d.getMinutes() << 5) | (d.getSeconds() >> 1), dosD = ((d.getFullYear() - 1980) << 9) | ((d.getMonth() + 1) << 5) | d.getDate();
    for (const { name, blob } of entries) {
      let nm = name; const k = nm.toLowerCase(); if (seen.has(k)) { const i = seen.get(k) + 1; seen.set(k, i); nm = nm.replace(/(\.[^.]+)?$/, ` (${i})$1`); } else seen.set(k, 1);
      const data = new Uint8Array(await blob.arrayBuffer()), fn = enc.encode(nm), c = crc32(data);
      const h = new DataView(new ArrayBuffer(30)); [[0, 0x04034b50, 4], [4, 20, 2], [6, 0x0800, 2], [8, 0, 2], [10, dosT, 2], [12, dosD, 2], [14, c, 4], [18, data.length, 4], [22, data.length, 4], [26, fn.length, 2], [28, 0, 2]].forEach(([o, v, s]) => (s === 4 ? h.setUint32(o, v, true) : h.setUint16(o, v, true)));
      parts.push(h.buffer, fn, data);
      const cd = new DataView(new ArrayBuffer(46)); [[0, 0x02014b50, 4], [4, 20, 2], [6, 20, 2], [8, 0x0800, 2], [10, 0, 2], [12, dosT, 2], [14, dosD, 2], [16, c, 4], [20, data.length, 4], [24, data.length, 4], [28, fn.length, 2], [30, 0, 2], [32, 0, 2], [34, 0, 2], [36, 0, 2], [38, 0, 4], [42, off, 4]].forEach(([o, v, s]) => (s === 4 ? cd.setUint32(o, v, true) : cd.setUint16(o, v, true)));
      central.push(cd.buffer, fn); off += 30 + fn.length + data.length;
    }
    const size = central.reduce((n, b) => n + (b.byteLength ?? b.length), 0), end = new DataView(new ArrayBuffer(22));
    [[0, 0x06054b50, 4], [8, entries.length, 2], [10, entries.length, 2], [12, size, 4], [16, off, 4]].forEach(([o, v, s]) => (s === 4 ? end.setUint32(o, v, true) : end.setUint16(o, v, true)));
    return new Blob([...parts, ...central, end.buffer], { type: 'application/zip' });
  }

  // ---------- download ----------
  const save = (blob, name) => { const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = name.replace(/[\\/:*?"<>|]/g, '_'); document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(a.href), 4000); };
  let last = null;   // the most recent download, for tests and for "Show in folder" later
  async function download(files) {
    if (!files.length) return;
    X().toast(files.length > 1 ? `Preparing ${files.length} files…` : `Preparing “${files[0].name}”…`);
    const got = await Promise.all(files.map(bytesFor)), anySample = got.some((g) => !g.real);
    if (got.length === 1) { save(got[0].blob, got[0].name); last = { name: got[0].name, size: got[0].blob.size, type: got[0].blob.type, real: got[0].real };
      X().toast(got[0].real ? `Downloaded “${got[0].name}”` : `Downloaded “${got[0].name}” — sample content, the platform sends the stored file`); return last; }
    const z = await zip(got.map((g) => ({ name: g.name, blob: g.blob }))), name = `XENO Library — ${files.length} files.zip`;
    save(z, name); last = { name, size: z.size, type: z.type, entries: got.map((g) => g.name), real: !anySample };
    X().toast(`Downloaded ${files.length} files as one zip${anySample ? ' — sample files carry sample content' : ''}`); return last;
  }
  window.XENO_FILES = { put, get, del, bytesFor, download, zip, last: () => last };
})();
