/* XENO_SETTINGS — the account centre (MODES SPEC §7j). One full page, one address per section, personal and workspace
 * sections in one nav. Everything here changes real state (the local store stands in for the API named in each footer)
 * and survives a reload. Passwords are never handled here (AUTH L1) — the sign-in origin owns them.
 */
(() => {
  const X = () => window.XW, D = () => window.XD;
  const esc = (s) => String(s ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
  const ic = (k) => X().ic(k);
  const LS = { get(k, d) { try { const v = localStorage.getItem('xw.' + k); return v == null ? d : JSON.parse(v); } catch { return d; } }, set(k, v) { try { localStorage.setItem('xw.' + k, JSON.stringify(v)); } catch {} } };
  const now = () => Date.now(), DAY = 864e5, ago = (t) => { const m = Math.round((now() - t) / 6e4); return m < 1 ? 'just now' : m < 60 ? `${m} min ago` : m < 1440 ? `${Math.round(m / 60)} h ago` : `${Math.round(m / 1440)} d ago`; };
  const when = (t) => new Date(t).toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' });
  const rid = () => Math.random().toString(36).slice(2, 10);
  const DEF = () => ({
    profile: { name: 'Emilian', handle: 'emilian', email: 'emilian@xenostudio.ai', verified: true, bio: '', photo: null },
    methods: [{ id: 'm1', kind: 'Google', who: 'emilian@xenostudio.ai', added: now() - 200 * DAY }, { id: 'm0', kind: 'Email and password', who: 'emilian@xenostudio.ai', added: now() - 400 * DAY }],
    passkeys: [{ id: 'pk1', name: 'This computer', added: now() - 30 * DAY, used: now() - DAY }], totp: false, codes: null, codesLeft: 0,
    sessions: [{ id: 's0', device: 'Chrome on Windows', where: 'Bucharest, RO', last: now(), current: true }, { id: 's1', device: 'XENO Hub on Windows', where: 'Bucharest, RO', last: now() - 2 * 3600e3 }, { id: 's2', device: 'Safari on iPhone', where: 'Bucharest, RO', last: now() - 3 * DAY }, { id: 's3', device: 'Firefox on Linux', where: 'Frankfurt, DE', last: now() - 19 * DAY }],
    apps: [{ id: 'a1', name: 'XENO Canvas', scope: 'Your profile, Library, credits', last: now() - DAY }, { id: 'a2', name: 'XENO Agent CLI', scope: 'Your profile, agents, credits', last: now() - 5 * DAY }],
    apiKeys: [{ id: 'k1', name: 'CI pipeline', fp: 'xk_…7f3a', scope: 'Agents · run', created: now() - 60 * DAY, expires: now() + 30 * DAY, used: now() - 3600e3 }],
    providers: [], route: {},
    plan: { name: 'Pro', price: '€20 / month', renews: now() + 12 * DAY, allowance: 72, payg: false, card: 'Visa ending 4242' },
    invoices: [[now() - 18 * DAY, '€20.00', 'Paid'], [now() - 48 * DAY, '€20.00', 'Paid'], [now() - 79 * DAY, '€20.00', 'Paid']],
    cap: null, balance: 2380, gifts: [],
    region: { lang: 'en', region: (navigator.language || 'en-GB').split('-')[1] || 'GB', tz: Intl.DateTimeFormat().resolvedOptions().timeZone },
    exportJob: null, deletion: null,
  });
  const A = () => { const a = { ...DEF(), ...(LS.get('acct', {}) || {}) }; return a; };
  const save = (a) => { LS.set('acct', a); };
  const edit = (fn, msg) => { const a = A(); fn(a); save(a); return window.XENO_NET ? window.XENO_NET.end(() => { X().render(); if (msg) X().toast(msg); }) : (X().render(), msg && X().toast(msg), Promise.resolve(true)); };
  const undoT = (msg, fn) => window.XENO_HIST.record(msg, fn);

  // ---------- confirm it's you (step-up): passkey or an authenticator code, then 10 minutes unlocked ----------
  async function stepUp(why) {
    if (+(sessionStorage.getItem('xw.stepUp') || 0) > now()) return true;
    const a = A(), opts = [...(a.passkeys.length ? [['passkey', 'Use a passkey']] : []), ...(a.totp ? [['totp', 'Authenticator code']] : []), ...(!a.passkeys.length && !a.totp ? [['email', 'Email me a code']] : [])];
    const v = await D().form({ title: 'Confirm it’s you', sub: why, submit: 'Confirm', size: 'sm', fields: [
      { id: 'how', label: 'With', type: 'seg', value: opts[0][0], options: opts },
      { id: 'code', label: 'Code', placeholder: 'Only for a code — 6 digits', validate: (x, all) => (all.how === 'passkey' || /^\d{6}$/.test((x || '').trim()) ? null : 'Enter the 6-digit code.') }] });
    if (!v) return false;
    sessionStorage.setItem('xw.stepUp', String(now() + 10 * 6e4)); return true;
  }

  // ---------- the sections ----------
  const SECT = [
    ['Personal', [['profile', 'Profile', 'user'], ['security', 'Sign-in & security', 'lock'], ['sessions', 'Sessions & devices', 'hub'], ['apps', 'Apps & sign-in methods', 'flow'], ['keys', 'API keys', 'code'], ['providers', 'Provider keys & inference', 'box']]],
    ['Billing', [['plan', 'Plan & billing', 'star'], ['usage', 'Usage & limits', 'chart'], ['gifts', 'Gifts', 'send']]],
    ['Preferences', [['general', 'General', 'gear'], ['appearance', 'Appearance', 'palette'], ['notifications', 'Notifications', 'bell'], ['modes', 'Modes', 'layers'], ['keyboard', 'Keyboard', 'terminal'], ['region', 'Language & region', 'globe']]],
    ['Privacy', [['data', 'Your data', 'download'], ['danger', 'Delete account', 'trash']]],
    ['Workspace', [['workspace', 'Workspace', 'building'], ['connections', 'Connections', 'share']]],
  ];
  const ALIAS = { account: 'profile', privacy: 'data' };
  const allIds = SECT.flatMap(([, s]) => s.map(([id]) => id));
  const title = (id) => SECT.flatMap(([, s]) => s).find(([x]) => x === id)?.[1] || 'Settings';
  const card = (h, body, acts = '') => `<section class="set-card">${h ? `<header><h3>${h}</h3>${acts}</header>` : ''}${body}</section>`;
  const row = (t, sub, ctl) => `<div class="set-row"><span><b>${t}</b>${sub ? `<small>${sub}</small>` : ''}</span><span class="set-ctl">${ctl}</span></div>`;
  const b = (label, act, arg = '', cls = 'ghost') => `<button class="pg-btn ${cls}" data-set="${act}" data-arg="${esc(arg)}"><span>${esc(label)}</span></button>`;
  const tag = (t, cls = '') => `<span class="set-tag ${cls}">${esc(t)}</span>`;
  const sw = (key, on) => `<button class="xd-sw" role="switch" aria-checked="${!!on}" data-set="pref" data-arg="${key}"><i></i></button>`;
  const seg = (key, cur, opts) => `<span class="xd-seg" role="radiogroup">${opts.map(([v, l]) => `<button type="button" role="radio" aria-checked="${String(cur) === String(v)}" data-set="prefv" data-arg="${key}=${v}">${esc(l)}</button>`).join('')}</span>`;

  const S = {
    profile: (a) => card('', `<div class="set-id"><span class="set-av">${esc(a.profile.name[0])}</span><div><b>${esc(a.profile.name)}</b><small>@${esc(a.profile.handle)} · ${esc(a.profile.email)}</small></div>${b('Edit profile', 'editProfile', '', '')}</div>`)
      + card('Profile', row('Display name', '', esc(a.profile.name)) + row('Handle', 'Your login, your @xenostudio.ai address and how people find you', '@' + esc(a.profile.handle)) + row('Email', a.profile.verified ? 'Verified' : 'Not verified — check your inbox', esc(a.profile.email) + ' ' + b('Change', 'changeEmail')) + row('Bio', '', a.profile.bio ? esc(a.profile.bio) : '<span class="pg-dim">Not set</span>')),
    security: (a) => card('Password', row('Password', 'Passwords are checked only on the XENO sign-in page, never inside an app', b('Change on xenostudio.ai', 'password')))
      + card('Two-step sign-in', row('Passkeys', a.passkeys.length ? `${a.passkeys.length} saved — sign in with your fingerprint, face or device PIN` : 'The strongest option: nothing to type, nothing to steal', b('Add a passkey', 'addPasskey', '', a.passkeys.length ? 'ghost' : ''))
        + a.passkeys.map((p) => row(`${ic('lock')} ${esc(p.name)}`, `Added ${when(p.added)} · used ${ago(p.used)}`, b('Remove', 'removePasskey', p.id))).join('')
        + row('Authenticator app', a.totp ? 'On — codes from your authenticator app' : 'Codes from an app like 1Password or Google Authenticator', a.totp ? b('Turn off', 'totpOff') : b('Set up', 'totpOn'))
        + row('Recovery codes', a.codes ? `${a.codesLeft} of 10 left — each works once if you lose your devices` : 'Created when you turn on two-step sign-in', a.codes ? b('Make new codes', 'codes') : (a.passkeys.length || a.totp ? b('Create', 'codes') : '')))
      + card('Sign-in methods', a.methods.map((m) => row(esc(m.kind), `${esc(m.who)} · added ${when(m.added)}`, a.methods.length > 1 ? b('Remove', 'removeMethod', m.id) : tag('Only method'))).join('') + row('', '', b('Connect Google, Apple or GitHub', 'addMethod'))),
    sessions: (a) => card('Signed-in devices', a.sessions.map((s) => row(`${esc(s.device)}${s.current ? ' ' + tag('This device', 'on') : ''}`, `${esc(s.where)} · ${s.current ? 'active now' : 'last active ' + ago(s.last)}`, s.current ? '' : b('Sign out', 'endSession', s.id))).join(''), a.sessions.length > 1 ? b('Sign out everywhere else', 'endOthers') : ''),
    apps: (a) => card('Apps you’re signed into', a.apps.length ? a.apps.map((x) => row(esc(x.name), `Can see: ${esc(x.scope)} · used ${ago(x.last)}`, b('Remove access', 'removeApp', x.id))).join('') : '<p class="pg-dim">No apps have access to your account.</p>')
      + card('Sign-in methods', `<p class="pg-dim set-p">Google, Apple and GitHub sign-in are managed in <a data-set="go" data-arg="security">Sign-in & security</a>.</p>`)
      + card('Connections', `<p class="pg-dim set-p">Services your workspace connects to (Drive, Slack, GitHub…) live in <a data-set="go" data-arg="connections">Connections</a>.</p>`),
    keys: (a) => card('API keys', (a.apiKeys.length ? a.apiKeys.map((k) => row(esc(k.name), `<code>${esc(k.fp)}</code> · ${esc(k.scope)} · ${k.expires ? (k.expires < now() ? 'expired' : 'expires ' + when(k.expires)) : 'never expires'} · ${k.used ? 'used ' + ago(k.used) : 'never used'}`, b('Revoke', 'revokeKey', k.id))).join('') : '<p class="pg-dim set-p">No keys. A key lets a script or CI pipeline act as you.</p>'), b('New API key', 'newKey', '', ''))
      + `<p class="pg-rule">${ic('lock')}A key is shown once, when you create it. After that only its last characters are kept — copy it then.</p>`,
    providers: (a) => { const P = X().PR, prods = Object.values(P).filter((p) => p.status !== 'soon' && !/^tool-/.test(p.id)).slice(0, 12);
      return card('Your provider keys', (a.providers.length ? a.providers.map((k) => row(esc(k.provider), `<code>${esc(k.fp)}</code> · added ${when(k.added)}${k.checked ? ' · works' : ''}`, b('Remove', 'removeProvider', k.id))).join('') : '<p class="pg-dim set-p">Bring your own OpenAI, Anthropic or Google key to pay those providers directly.</p>'), b('Add a key', 'addProvider', '', ''))
        + card('Where each product’s AI comes from', prods.map((p) => { const cur = a.route[p.id] || 'credits'; return row(esc(p.name), cur === 'credits' ? 'Charged to your XENO credits' : cur === 'byok' ? 'Your own key — billed by the provider' : 'XENO’s in-house models', `<span class="xd-seg" role="radiogroup">${[['credits', 'XENO'], ['byok', 'Your key'], ['house', 'In-house']].map(([v, l]) => `<button type="button" role="radio" aria-checked="${cur === v}" data-set="route" data-arg="${p.id}=${v}"${v === 'byok' && !a.providers.length ? ' aria-disabled="true" title="Add a provider key first"' : ''}>${l}</button>`).join('')}</span>`); }).join(''))
        + `<p class="pg-rule">${ic('lock')}Your keys are stored encrypted and never shown again — only a fingerprint, so you can tell them apart.</p>`; },
    plan: (a) => card('Plan', row(`${esc(a.plan.name)} ${tag(a.plan.price)}`, a.plan.cancelAt ? `Ends ${when(a.plan.cancelAt)} — you keep it until then` : `Renews ${when(a.plan.renews)}`, (a.plan.cancelAt ? b('Keep my plan', 'resumePlan') : b('Cancel plan', 'cancelPlan')) + b('Change plan', 'changePlan', '', '')) + row('Payment method', '', esc(a.plan.card) + ' ' + b('Update', 'card')))
      + card('Invoices', a.invoices.map(([t, amt, st]) => row(when(t), esc(st), `${esc(amt)} ${b('Download', 'invoice', String(t))}`)).join('')),
    usage: (a) => (a.plan.payg ? card('Credits', row('Balance', 'Credits pay for AI, rendering and hosted agents', `<b class="set-big">${a.balance.toLocaleString()}</b> ${b('Buy credits', 'buy', '', '')}`)) : card(`${esc(a.plan.name)} allowance`, row('This month', `Resets ${when(a.plan.renews)}`, `<span class="set-meter" style="--v:${a.plan.allowance}%"><i></i></span><b>${a.plan.allowance}% used</b>`)))
      + card('Monthly limit', row('Spend cap', a.cap ? `Work that would go past ${a.cap.toLocaleString()} credits this month waits for you` : 'No limit — usage beyond your plan is charged as you go', (a.cap ? b('Remove limit', 'capOff') : '') + b(a.cap ? 'Change' : 'Set a limit', 'cap', '', a.cap ? 'ghost' : '')))
      + card('By product this month', [['Canvas', 31], ['Chat', 24], ['Agent', 18], ['Motion', 9]].map(([n, v]) => row(n, '', `<span class="set-meter" style="--v:${v * 2}%"><i></i></span><b>${v}%</b>`)).join('')),
    gifts: (a) => card('Send credits', `<p class="pg-dim set-p">Give credits from your balance to anyone on XENO. If they don’t accept within 30 days, the credits come back.</p>`, b('Send a gift', 'gift', '', ''))
      + card('Sent', a.gifts.length ? a.gifts.map((g) => row(`${g.amount.toLocaleString()} credits to @${esc(g.to)}`, `${esc(g.note || 'No message')} · ${when(g.at)}`, g.state === 'pending' ? `${tag('Waiting')} ${b('Take back', 'ungift', g.id)}` : tag(g.state === 'returned' ? 'Returned' : 'Accepted', 'on'))).join('') : '<p class="pg-dim set-p">No gifts yet.</p>'),
    general: () => { const p = D().prefs(); return card('Starting up', row('Open to', 'What you see when you open XENO', seg('startIn', p.startIn, [['last', 'Where I left off'], ['overview', 'Overview'], ['default', 'My default mode']])) + row('Links to other products', '', seg('links', p.links, [['same', 'Same window'], ['new', 'New window']]))); },
    appearance: () => { const p = D().prefs(); return card('Appearance', row('Text size', '', seg('text', p.text, [['small', 'Small'], ['default', 'Default'], ['large', 'Large']])) + row('Density', '', seg('density', p.density, [['compact', 'Compact'], ['comfortable', 'Comfortable']])) + row('Motion', 'Follow your system, or reduce animation', seg('motion', p.motion, [['system', 'System'], ['reduce', 'Reduced']])) + row('High contrast', '', sw('contrast', p.contrast)) + row('Shortcut hints on buttons', '', sw('hints', p.hints))); },
    notifications: () => { const p = D().prefs(); return card('Notifications', row('Desktop notifications', 'When something needs you', sw('ntDesktop', p.ntDesktop)) + row('Sound', '', sw('ntSound', p.ntSound)) + row('Email digest', 'What happened while you were away', seg('ntDigest', p.ntDigest, [['off', 'Off'], ['daily', 'Daily'], ['weekly', 'Weekly']])))
      + card('Launches you’re waiting for', (() => { const w = [...window.XL.watched()]; return w.length ? w.map((id) => row(esc(X().PR[id]?.name || id), 'You’ll be told the day it launches', `<button class="pg-btn ghost" data-xl-notify="${id}"><span data-xl-l>Notifying you</span></button>`)).join('') : '<p class="pg-dim set-p">Press “Notify me” on a product that isn’t out yet.</p>'; })()); },
    modes: () => card('Modes', `<p class="pg-dim set-p">Your default mode, order and logo cycle.</p>`, `<button class="pg-btn" data-set="manageModes"><span>Manage modes</span></button>`)
      + card('Your modes', window.XENO_CUSTOM.list().map((c) => row(esc(c.name), `${c.products.length} products`, `<button class="pg-btn ghost" data-xa="customMode" data-arg="${c.id}"><span>Edit</span></button>`)).join('') || '<p class="pg-dim set-p">None yet.</p>', `<button class="pg-btn ghost" data-xa="customMode"><span>New custom mode</span></button>`),
    keyboard: () => card('Keyboard', row('All shortcuts', 'Ctrl / shows them anywhere', `<button class="pg-btn ghost" data-set="shortcuts"><span>Show shortcuts</span></button>`) + [['Ctrl K', 'Search everything'], ['Ctrl ,', 'Settings'], ['Ctrl \\', 'Show or hide the sidebar'], ['F1', 'Report a problem'], ['Shift F10', 'Menu for what is focused']].map(([k, t]) => row(t, '', `<kbd>${k}</kbd>`)).join('')),
    region: (a) => { const sample = new Date(); const fmt = (l) => { try { return new Intl.DateTimeFormat(l, { dateStyle: 'medium', timeStyle: 'short', timeZone: a.region.tz }).format(sample) + ' · ' + new Intl.NumberFormat(l).format(12345.67); } catch { return ''; } };
      const loc = `${a.region.lang}-${a.region.region}`;
      return card('Language & region', row('Language', 'English first — more languages are on the way', `<select class="set-sel" data-set-sel="lang"><option value="en" selected>English</option><option disabled>Deutsch — coming</option><option disabled>Français — coming</option><option disabled>Română — coming</option><option disabled>Español — coming</option></select>`)
        + row('Region', 'Sets date, time and number formats', `<select class="set-sel" data-set-sel="region">${[['GB', 'United Kingdom'], ['US', 'United States'], ['DE', 'Germany'], ['FR', 'France'], ['RO', 'Romania'], ['ES', 'Spain'], ['AE', 'United Arab Emirates'], ['JP', 'Japan']].map(([v, n]) => `<option value="${v}"${a.region.region === v ? ' selected' : ''}>${n}</option>`).join('')}</select>`)
        + row('Time zone', 'Detected from this device', `<select class="set-sel" data-set-sel="tz">${[...new Set([a.region.tz, 'Europe/London', 'Europe/Bucharest', 'Europe/Berlin', 'America/New_York', 'America/Los_Angeles', 'Asia/Dubai', 'Asia/Tokyo'])].map((z) => `<option${z === a.region.tz ? ' selected' : ''}>${z}</option>`).join('')}</select>`)
        + row('Preview', '', `<span class="set-preview">${esc(fmt(loc))}</span>`)); },
    data: (a) => { const j = a.exportJob, ready = j && now() >= j.ready, exp = j && now() > j.ready + 7 * DAY;
      return card('Export your data', row('Everything you made', 'Files, projects, chats and settings as one ZIP. We prepare it in the background and tell you when it’s ready.', !j || exp ? b('Request export', 'export', '', '') : ready ? b('Download export', 'downloadExport', '', '') : `${tag('Preparing…')}`) + (j && !exp ? row('', ready ? `Ready — the link works until ${when(j.ready + 7 * DAY)}` : `Requested ${ago(j.at)}`, '') : ''))
        + card('Privacy', row('Help improve XENO', 'Share anonymous usage — never your files or chats', sw('analytics', D().prefs().analytics)) + row('Adaptive mode', 'What Adaptive may learn from how you work', `<button class="pg-btn ghost" data-set="adaptive"><span>Review</span></button>`)); },
    danger: (a) => a.deletion ? card('Your account is being deleted', `<p class="set-p">It will be permanently deleted on <b>${when(a.deletion.at + 30 * DAY)}</b>. Until then you can change your mind — everything comes back as it was.</p>`, b('Keep my account', 'undelete', '', ''))
      : card('Delete your account', `<p class="pg-dim set-p">Deletes your profile, files, chats and agents. You have 30 days to change your mind; after that it can’t be undone. Workspaces you own have to be handed over or deleted first.</p>`, b('Delete account…', 'delete', '', 'danger')),
    workspace: () => { const w = window.XA.currentWorkspace(); if (window.XENO_ROLE && !window.XENO_ROLE.can('manage')) return card('Workspace', row('Name', '', esc(w.name)) + row('Your role', '', esc(window.XENO_ROLE.role() === 'guest' ? 'Guest — you see only what was shared with you' : 'Member')) + '<p class="pg-dim wf-note">Owners and admins manage this workspace’s settings.</p>'); return card('Workspace', row('Name', '', esc(w.name)) + row('Your role', '', esc(w.sub)) + row('Members, agents and teams', '', `<button class="pg-btn ghost" data-go="workspace"><span>Open workspace</span></button>`) + row('Switch or create', '', `<button class="pg-btn ghost" data-xa="newCompany"><span>Create a company</span></button>`)); },
    connections: () => { const C = LS.get('connections', [{ id: 'c1', name: 'Google Drive', by: 'Emilian', scope: 'Read files you pick', at: now() - 40 * DAY }, { id: 'c2', name: 'GitHub', by: 'Emilian', scope: 'Repositories: xeno-platform', at: now() - 12 * DAY }]);
      return card('Connected services', C.length ? C.map((c) => row(esc(c.name), `${esc(c.scope)} · by ${esc(c.by)} · ${when(c.at)}`, b('Disconnect', 'disconnect', c.id))).join('') : '<p class="pg-dim set-p">Nothing connected.</p>', b('Connect a service', 'connect', '', '')); },
  };
  const API = { profile: 'GET/PATCH /api/v2/me', security: '/api/v2/me/security (passkeys · totp · recovery-codes · identities)', sessions: 'GET/DELETE /api/v2/me/sessions', apps: 'GET/DELETE /api/v2/me/authorized-clients', keys: 'GET/POST/DELETE /api/v2/me/api-keys', providers: '/api/v2/me/provider-credentials · /api/v2/me/inference-routes', plan: '/api/v2/billing/subscription · /invoices', usage: '/api/v2/ledger/balance · /usage · /spend-cap', gifts: 'POST /api/v2/ledger/gifts', general: 'PATCH /api/v2/me/preferences', appearance: 'PATCH /api/v2/me/preferences', notifications: 'PATCH /api/v2/me/preferences', modes: '/api/v2/me/modes', keyboard: '', region: 'PATCH /api/v2/me/preferences', data: 'POST /api/v2/me/export', danger: 'POST /api/v2/me/deletion', workspace: 'GET /api/v2/workspaces/:id', connections: '/api/v2/workspaces/:id/connections' };

  function render(section) {
    const id = ALIAS[section] || (allIds.includes(section) ? section : 'profile'), a = A();
    // the sidebar IS the settings nav (one list, from SECT) — the page carries only the section
    const nav0 = `<nav class="set-nav" aria-label="Settings">${SECT.map(([g, s]) => `<div class="set-grp">${g}</div>${s.map(([sid, l, i]) => `<button class="set-nl" data-set="go" data-arg="${sid}" aria-current="${sid === id}">${ic(i)}<span>${esc(l)}</span></button>`).join('')}`).join('')}</nav>`;
    return `<div class="pg pg--set"><header class="pg-head pg-head--obj"><div class="pg-ttl"><small>Settings</small><h1>${esc(title(id))}</h1></div></header>
      <div class="set-wrap"><div class="set-body" data-set-body="${id}">${S[id](a)}</div></div><footer class="pg-foot" data-fam="settings" data-api="${esc(API[id] || '')}" data-noun=""></footer></div>`;
  }
  const go = (sid) => X().go('global', { global: 'settings', item: title(sid) });
  const idOf = (item) => SECT.flatMap(([, s]) => s).find(([, l]) => l === item)?.[0] || ALIAS[item] || item;

  // ---------- actions ----------
  const ACT = {
    go,
    password: () => window.open('https://xenostudio.ai/overview/settings', '_blank', 'noopener'),
    async editProfile() { const a = A(); const v = await D().form({ title: 'Edit profile', submit: 'Save', fields: [{ id: 'name', label: 'Display name', required: true, max: 60, value: a.profile.name }, { id: 'handle', label: 'Handle', required: true, max: 30, value: a.profile.handle, validate: (x) => (/^[a-z0-9][a-z0-9._-]{2,29}$/i.test(x.trim()) ? null : '3–30 letters, numbers, dots, dashes or underscores.') }, { id: 'bio', label: 'Bio', type: 'textarea', rows: 2, max: 160, value: a.profile.bio }] });
      if (v) edit((x) => { Object.assign(x.profile, { name: v.name.trim(), handle: v.handle.trim().toLowerCase(), bio: v.bio }); }, 'Profile saved'); },
    async changeEmail() { if (!await stepUp('Changing your email signs you out on every other device.')) return; const v = await D().form({ title: 'Change email', sub: 'We send a link to the new address. Your email changes when you open it.', submit: 'Send link', size: 'sm', fields: [{ id: 'e', label: 'New email', required: true, validate: (x) => (/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(x.trim()) ? null : 'Enter an email address.') }] });
      if (v) edit((x) => { x.profile.pending = v.e.trim(); }, `Link sent to ${v.e.trim()} — your email changes when you open it`); },
    async addPasskey() { if (!await stepUp('Adding a passkey changes how you sign in.')) return; const v = await D().form({ title: 'Add a passkey', sub: 'Your device will ask for your fingerprint, face or PIN.', submit: 'Create passkey', size: 'sm', fields: [{ id: 'n', label: 'Name it', required: true, value: navigator.userAgentData?.platform ? navigator.userAgentData.platform + ' computer' : 'This device', max: 40 }] });
      if (v) edit((x) => { x.passkeys.push({ id: 'pk' + rid(), name: v.n.trim(), added: now(), used: now() }); if (!x.codes) { x.codes = true; x.codesLeft = 10; } }, 'Passkey added'); },
    async removePasskey(id) { const a = A(); if (a.passkeys.length === 1 && !a.totp && !await D().confirm({ title: 'Remove your last passkey?', body: 'Two-step sign-in turns off. You’ll sign in with your password or Google only.', action: 'Remove' })) return; if (!await stepUp('Removing a passkey changes how you sign in.')) return; edit((x) => { x.passkeys = x.passkeys.filter((p) => p.id !== id); }, 'Passkey removed'); },
    async totpOn() { if (!await stepUp('Turning on an authenticator changes how you sign in.')) return; const secret = Array.from({ length: 16 }, () => 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'[Math.floor(Math.random() * 32)]).join('');
      const v = await D().form({ title: 'Set up an authenticator app', sub: 'Add this key in your authenticator app, then type the 6-digit code it shows.', submit: 'Turn on', size: 'sm', aside: `<div class="set-secret"><code>${secret.match(/.{4}/g).join(' ')}</code><small>otpauth://totp/XENO:${esc(A().profile.handle)}?secret=${secret}&issuer=XENO</small></div>`, fields: [{ id: 'code', label: 'Code from the app', required: true, validate: (x) => (/^\d{6}$/.test(x.trim()) ? null : 'Enter the 6-digit code.') }] });
      if (v) { edit((x) => { x.totp = true; if (!x.codes) { x.codes = true; x.codesLeft = 10; } }); ACT.codes(true); } },
    async totpOff() { if (!await D().confirm({ title: 'Turn off the authenticator app?', body: 'You’ll no longer be asked for its codes.', action: 'Turn off', danger: false })) return; if (!await stepUp('Turning off two-step sign-in makes your account easier to take over.')) return; edit((x) => { x.totp = false; }, 'Authenticator turned off'); },
    async codes(fresh) { if (!fresh && !await stepUp('New recovery codes replace the old ones.')) return; const list = Array.from({ length: 10 }, () => `${rid().slice(0, 4)}-${rid().slice(0, 4)}`);
      edit((x) => { x.codes = true; x.codesLeft = 10; });
      D().info({ title: 'Your recovery codes', sub: 'Each works once. Keep them somewhere safe — they’re shown only now.', html: `<ol class="set-codes">${list.map((c) => `<li><code>${c}</code></li>`).join('')}</ol>`, actions: [{ label: 'Copy', close: false, run: () => window.XCM.H.copy(list.join('\n'), 'Codes copied') }, { label: 'Download', close: false, run: () => { const a2 = document.createElement('a'); a2.href = URL.createObjectURL(new Blob([`XENO recovery codes for @${A().profile.handle}\n\n${list.join('\n')}\n`], { type: 'text/plain' })); a2.download = 'xeno-recovery-codes.txt'; a2.click(); } }] }); },
    async removeMethod(id) { const m = A().methods.find((x) => x.id === id); if (!await D().confirm({ title: `Remove ${esc(m.kind)} sign-in?`, body: 'You’ll no longer be able to sign in with it. Other devices are signed out for safety.', action: 'Remove' })) return; if (!await stepUp('Removing a sign-in method changes how you sign in.')) return; edit((x) => { x.methods = x.methods.filter((y) => y.id !== id); x.sessions = x.sessions.filter((s) => s.current); }, `${m.kind} removed — other devices were signed out`); },
    async addMethod() { const v = await D().form({ title: 'Add a sign-in method', submit: 'Continue', size: 'sm', fields: [{ id: 'k', label: 'Sign in with', type: 'seg', value: 'Apple', options: [['Google', 'Google'], ['Apple', 'Apple'], ['GitHub', 'GitHub']] }] }); if (!v) return; if (A().methods.some((m) => m.kind === v.k)) return X().toast(`${v.k} is already connected`); edit((x) => { x.methods.unshift({ id: 'm' + rid(), kind: v.k, who: x.profile.email, added: now() }); }, `${v.k} sign-in connected`); },
    endSession(id) { const s = A().sessions.find((x) => x.id === id); edit((x) => { x.sessions = x.sessions.filter((y) => y.id !== id); }, `Signed out ${s.device}`); },
    async endOthers() { if (!await D().confirm({ title: 'Sign out everywhere else?', body: 'Every other device and app is signed out. This one stays signed in.', action: 'Sign out others', danger: false })) return; edit((x) => { x.sessions = x.sessions.filter((s) => s.current); }, 'Signed out of every other device'); },
    async removeApp(id) { const x0 = A().apps.find((y) => y.id === id); if (!await D().confirm({ title: `Remove ${esc(x0.name)}’s access?`, body: 'It’s signed out and has to ask again before it can use your account.', action: 'Remove access' })) return; edit((x) => { x.apps = x.apps.filter((y) => y.id !== id); }, `${x0.name} no longer has access`); },
    async newKey() { if (!await stepUp('An API key can act as you.')) return;
      const v = await D().form({ title: 'New API key', submit: 'Create key', size: 'sm', fields: [{ id: 'name', label: 'Name', required: true, max: 40, placeholder: 'e.g. CI pipeline' }, { id: 'scope', label: 'It can', type: 'seg', value: 'read', options: [['read', 'Read'], ['run', 'Run agents'], ['full', 'Everything']] }, { id: 'exp', label: 'Expires', type: 'seg', value: '90', options: [['30', '30 days'], ['90', '90 days'], ['365', '1 year'], ['0', 'Never']] }] });
      if (!v) return; const secret = 'xk_live_' + Array.from({ length: 4 }, rid).join(''), fp = 'xk_…' + secret.slice(-4);
      edit((x) => { x.apiKeys.unshift({ id: 'k' + rid(), name: v.name.trim(), fp, scope: { read: 'Read', run: 'Agents · run', full: 'Everything' }[v.scope], created: now(), expires: +v.exp ? now() + +v.exp * DAY : null, used: null }); });
      D().info({ title: 'Copy your new key', sub: 'This is the only time it’s shown.', html: `<div class="set-secret"><code data-secret>${secret}</code></div><p class="xd-note">Store it in your password manager or CI secrets. If you lose it, revoke it and make a new one.</p>`, actions: [{ label: 'Copy key', close: false, run: () => window.XCM.H.copy(secret, 'Key copied') }] }); },
    async revokeKey(id) { const k = A().apiKeys.find((x) => x.id === id); if (!await D().confirm({ title: `Revoke “${esc(k.name)}”?`, body: 'Anything using it stops working immediately.', action: 'Revoke key' })) return; edit((x) => { x.apiKeys = x.apiKeys.filter((y) => y.id !== id); }, `Revoked ${k.name}`); },
    async addProvider() { const v = await D().form({ title: 'Add a provider key', sub: 'Stored encrypted. After this, only a fingerprint is shown.', submit: 'Add key', size: 'sm', fields: [{ id: 'p', label: 'Provider', type: 'seg', value: 'OpenAI', options: [['OpenAI', 'OpenAI'], ['Anthropic', 'Anthropic'], ['Google', 'Google']] }, { id: 'k', label: 'Key', required: true, validate: (x) => (x.trim().length >= 20 ? null : 'That doesn’t look like a full key.') }] });
      if (!v) return; const k = v.k.trim(); edit((x) => { x.providers.push({ id: 'pv' + rid(), provider: v.p, fp: k.slice(0, 3) + '…' + k.slice(-4), added: now(), checked: true }); }, `${v.p} key added`); },
    async removeProvider(id) { const p = A().providers.find((x) => x.id === id); if (!await D().confirm({ title: `Remove your ${esc(p.provider)} key?`, body: 'Products using it go back to XENO credits.', action: 'Remove key' })) return; edit((x) => { x.providers = x.providers.filter((y) => y.id !== id); Object.keys(x.route).forEach((k) => { if (x.route[k] === 'byok' && !x.providers.length) x.route[k] = 'credits'; }); }, 'Key removed'); },
    route(arg) { const [p, v] = arg.split('='); if (v === 'byok' && !A().providers.length) return X().toast('Add a provider key first'); edit((x) => { x.route[p] = v; }, `${X().PR[p].name}: ${{ credits: 'XENO credits', byok: 'your own key', house: 'in-house models' }[v]}`); },
    changePlan: () => window.open('https://xenostudio.ai/pricing', '_blank', 'noopener'),
    async cancelPlan() { const a = A(); if (!await D().confirm({ title: `Cancel ${esc(a.plan.name)}?`, body: `You keep it until ${when(a.plan.renews)}. Nothing is deleted — you move to the free plan after that.`, action: 'Cancel plan' })) return; edit((x) => { x.plan.cancelAt = x.plan.renews; }, `${a.plan.name} ends ${when(a.plan.renews)}`); },
    resumePlan: () => edit((x) => { delete x.plan.cancelAt; }, 'Your plan continues'),
    card: () => window.open('https://xenostudio.ai/overview/billing', '_blank', 'noopener'),
    invoice(t) { const inv = A().invoices.find(([x]) => String(x) === t); const a2 = document.createElement('a'); a2.href = URL.createObjectURL(new Blob([`XENO invoice\n${when(inv[0])}\nPlan: ${A().plan.name}\nAmount: ${inv[1]}\nStatus: ${inv[2]}\n`], { type: 'text/plain' })); a2.download = `xeno-invoice-${new Date(inv[0]).toISOString().slice(0, 10)}.txt`; a2.click(); X().toast('Invoice downloaded'); },
    buy: () => window.XA.buyCredits(),
    async cap() { const v = await D().form({ title: 'Monthly spend limit', sub: 'Work that would go past it waits for you to approve.', submit: 'Save limit', size: 'sm', fields: [{ id: 'n', label: 'Credits per month', type: 'number', required: true, value: String(A().cap || 5000), validate: (x) => (/^\d+$/.test(x) && +x > 0 ? null : 'Enter a whole number.') }] }); if (v) edit((x) => { x.cap = +v.n; }, `Limit set to ${(+v.n).toLocaleString()} credits a month`); },
    capOff: () => edit((x) => { x.cap = null; }, 'Spend limit removed'),
    async gift() { const a = A(); const v = await D().form({ title: 'Send credits', sub: `You have ${a.balance.toLocaleString()} credits.`, submit: 'Send gift', size: 'sm', fields: [{ id: 'to', label: 'To', required: true, placeholder: '@handle', validate: (x) => { const h = x.trim().replace(/^@/, ''); return !/^[a-z0-9._-]{3,30}$/i.test(h) ? 'Enter their handle.' : h === a.profile.handle ? 'That’s you.' : null; } }, { id: 'n', label: 'Credits', type: 'number', required: true, value: '500', validate: (x) => (!/^\d+$/.test(x) || +x <= 0 ? 'Enter a whole number.' : +x > a.balance ? 'More than you have.' : null) }, { id: 'note', label: 'Message', type: 'textarea', rows: 2, max: 140 }] });
      if (v) edit((x) => { x.balance -= +v.n; x.gifts.unshift({ id: 'g' + rid(), to: v.to.trim().replace(/^@/, ''), amount: +v.n, note: v.note, at: now(), state: 'pending' }); }, `Sent ${(+v.n).toLocaleString()} credits to @${v.to.trim().replace(/^@/, '')} — they have 30 days to accept`); },
    ungift(id) { edit((x) => { const g = x.gifts.find((y) => y.id === id); g.state = 'returned'; x.balance += g.amount; }, 'Gift taken back — the credits are yours again'); },
    pref(k) { const p = D().prefs(); p[k] = !p[k]; LS.set('prefs', p); D().applyPrefs(); return window.XENO_NET ? window.XENO_NET.end(() => X().render()) : X().render(); },
    prefv(arg) { const [k, v] = arg.split('='); const p = D().prefs(); p[k] = v; LS.set('prefs', p); D().applyPrefs(); X().render(); },
    manageModes: () => { document.querySelector('#logo')?.dispatchEvent(new MouseEvent('contextmenu', { bubbles: true, cancelable: true })); setTimeout(() => document.querySelector('[data-manage]')?.click(), 300); },
    shortcuts: () => X().openShortcuts(),
    adaptive: () => X().openAdConsent?.(),
    export() { edit((x) => { x.exportJob = { at: now(), ready: now() + 8000 }; }, 'Export requested — we’ll tell you when it’s ready'); setTimeout(() => { X().render(); X().toast('Your export is ready to download'); }, 8200); },
    async downloadExport() { const items = window.XENO_PG_LIBRARY.items.filter((f) => !f.trashedAt).slice(0, 6); const extra = [{ name: 'projects.json', blob: new Blob([JSON.stringify(window.XENO_PG_PROJECTS.items, null, 2)]) }, { name: 'settings.json', blob: new Blob([JSON.stringify({ account: { ...A(), apiKeys: A().apiKeys.map(({ fp, name }) => ({ fp, name })) }, preferences: D().prefs() }, null, 2)]) }];
      const files = await Promise.all(items.map(window.XENO_FILES.bytesFor)); const z = await window.XENO_FILES.zip([...files.map((f) => ({ name: 'files/' + f.name, blob: f.blob })), ...extra]);
      const a2 = document.createElement('a'); a2.href = URL.createObjectURL(z); a2.download = `xeno-export-${A().profile.handle}.zip`; a2.click(); X().toast('Export downloaded'); },
    async delete() { const a = A(), owned = window.XA.workspaces().filter((w) => w.id !== 'personal' && /owner/i.test(w.sub));   // every workspace you own, not only the open one
      if (owned.length) return D().confirm({ title: 'Hand over your workspace first', body: `You own ${owned.map((w) => esc(w.name)).join(', ')}. Make someone else the owner, or delete ${owned.length > 1 ? 'them' : 'it'}, before you delete your account.`, action: 'OK', danger: false });
      if (!await D().confirm({ title: 'Delete your account?', body: 'Your profile, files, chats and agents are deleted after 30 days. Sign in before then to keep everything.', action: 'Delete account', typeToConfirm: a.profile.handle })) return;
      if (!await stepUp('Deleting your account is permanent after 30 days.')) return; edit((x) => { x.deletion = { at: now() }; }, 'Your account will be deleted in 30 days'); },
    undelete: () => edit((x) => { x.deletion = null; }, 'Your account is staying'),
    async connect() { const v = await D().form({ title: 'Connect a service', submit: 'Connect', size: 'sm', fields: [{ id: 's', label: 'Service', type: 'choice', cols: 2, value: 'Slack', options: [['Slack', 'Slack', 'Messages and channels'], ['Notion', 'Notion', 'Pages you pick'], ['Dropbox', 'Dropbox', 'Files you pick'], ['Figma', 'Figma', 'Files you pick']] }] }); if (!v) return;
      const C = LS.get('connections', null) || [{ id: 'c1', name: 'Google Drive', by: 'Emilian', scope: 'Read files you pick', at: now() - 40 * DAY }, { id: 'c2', name: 'GitHub', by: 'Emilian', scope: 'Repositories: xeno-platform', at: now() - 12 * DAY }]; C.unshift({ id: 'c' + rid(), name: v.s, by: A().profile.name, scope: 'Read what you pick', at: now() }); LS.set('connections', C); X().render(); X().toast(`${v.s} connected`); },
    async disconnect(id) { const C = LS.get('connections', null) || []; const c = C.find((x) => x.id === id); if (!c || !await D().confirm({ title: `Disconnect ${esc(c.name)}?`, body: 'Agents and apps in this workspace lose access to it.', action: 'Disconnect' })) return; LS.set('connections', C.filter((x) => x.id !== id)); X().render(); undoT(`${c.name} disconnected`, () => { LS.set('connections', C); X().render(); }); },
  };
  document.addEventListener('click', (e) => { const t = e.target.closest('[data-set]'); if (!t || !t.closest('.pg--set')) return; e.preventDefault(); if (t.getAttribute('aria-disabled') === 'true') return X().toast(t.title || 'Not available'); window.XENO_NET?.begin('settings', t.dataset.set, t); Promise.resolve(ACT[t.dataset.set]?.(t.dataset.arg)).finally(() => window.XENO_NET?.clear(t)); });
  document.addEventListener('change', (e) => { const s = e.target.closest('[data-set-sel]'); if (!s) return; window.XENO_NET?.begin('settings', 'region', s); edit((x) => { x.region[s.dataset.setSel] = s.value; }, 'Saved'); });
  // the deletion grace period is real: signing in (opening XENO) while it runs offers to keep the account
  setTimeout(() => { const a = A(); if (a.deletion && window.XW) { const t = document.getElementById('toast'); t.innerHTML = `Your account is scheduled for deletion on ${when(a.deletion.at + 30 * DAY)} <button class="pg-undo">Keep my account</button>`; t.classList.add('on'); t.querySelector('.pg-undo').onclick = () => { ACT.undelete(); t.classList.remove('on'); }; } }, 1500);
  // the sidebar for Settings is the same nav, as rows (one source: SECT)
  window.XENO_GLOBAL_NAV.settings = ['Settings', 'You and your workspace', '', SECT.map(([g, s]) => [g, s.map(([, l]) => [l, ''])])];
  window.XENO_SETTINGS = { render: (item) => render(idOf(item || 'Profile')), go, idOf, stepUp, sections: () => allIds, open: (sec) => go(ALIAS[sec] || sec || 'profile') };
})();
