import { createRequire } from 'node:module'; import path from 'node:path'; import { pathToFileURL } from 'node:url';
const require = createRequire(import.meta.url); const puppeteer = require('puppeteer');
const b = await puppeteer.launch({ headless: true, args: ['--allow-file-access-from-files'] }); const p = await b.newPage(); const errs = []; p.on('pageerror', (e) => errs.push(e.message));
const url = pathToFileURL(path.resolve('index.html')).href, wait = (ms) => new Promise((r) => setTimeout(r, ms));
let fails = 0; const ok = (c, m) => { if (!c) fails++; console.log(c ? 'PASS' : 'FAIL', m); }; const ev = (f) => p.evaluate(f);
await p.setViewport({ width: 1440, height: 900, deviceScaleFactor: 2 }); await p.goto(url); await ev(() => { localStorage.clear(); localStorage.setItem('xw.introSeen', JSON.stringify({ studio: 1, office: 1, social: 1, corpo: 1, dev: 1, tools: 1 })); }); await p.goto(url + '#/studio'); await wait(900);
await p.click('#rail [data-go="account"]'); await wait(400);
const g = await ev(() => { const m = document.getElementById('menu'), r = m.getBoundingClientRect(), rail = document.getElementById('rail').getBoundingClientRect(); return { w: Math.round(r.width), l: Math.round(r.left - rail.right), b: Math.round(innerHeight - r.bottom), role: m.getAttribute('role'), f: document.activeElement.dataset.fk, ov: (() => { const s = m; return s.scrollHeight - s.clientHeight; })() }; });
ok(g.w === 300 && g.l === 7 && g.b === 7 && g.role === 'dialog', `account: dialog ${g.w}px, 7/7 gaps`);
ok(g.f === 'wpersonal', 'focus starts on the current workspace');
await p.screenshot({ path: 'acc.png', clip: await ev(() => { const r = document.getElementById('menu').getBoundingClientRect(); return { x: 0, y: r.top - 12, width: 420, height: r.height + 24 }; }) });
await p.keyboard.press('ArrowDown'); ok(await ev(() => document.activeElement.dataset.fk === 'wbunker'), 'arrow keys move through the list');
await p.hover('[data-ws="bunker"]'); await wait(200); await p.screenshot({ path: 'acc-hover.png', clip: await ev(() => { const r = document.getElementById('menu').getBoundingClientRect(); return { x: 0, y: r.top - 12, width: 420, height: r.height + 24 }; }) });
await p.click('[data-ws="bunker"]'); await wait(300);
ok(await ev(() => document.querySelector('#rail .avatar').textContent === 'B' && !document.getElementById('menu').classList.contains('on')), 'switching workspace updates the rail avatar and closes');
await p.click('#rail [data-go="account"]'); await wait(400);
ok(await ev(() => document.querySelector('.acc-ws.on')?.dataset.ws === 'bunker'), 'the switched workspace is now marked current');
await p.click('[data-act="plan"]'); await wait(400);
ok(await ev(() => document.getElementById('menu').dataset.owner === 'usage'), 'Plan & credits opens the Usage popover');
await p.keyboard.press('Escape'); await wait(300);
await p.click('#rail [data-go="account"]'); await wait(300); await p.keyboard.press('Escape'); await wait(300);
ok(await ev(() => document.activeElement === document.querySelector('#rail [data-go="account"]')), 'Esc returns focus to the avatar');
await p.click('#rail [data-go="account"]'); await wait(400);
const ft = await ev(() => { const f = document.querySelector('.acc-foot'), c = f.querySelector('.acc-close').getBoundingClientRect(), o = f.querySelector('.acc-out').getBoundingClientRect(), r = f.getBoundingClientRect(); return { closeLeft: c.left - r.left < 12, outRight: r.right - o.right < 12, icon: !!f.querySelector('.acc-out svg path') }; });
ok(ft.closeLeft && ft.outRight && ft.icon, 'footer: Close on the left, Sign out with a leave icon on the right');
await p.screenshot({ path: 'acc.png', clip: await ev(() => { const r = document.getElementById('menu').getBoundingClientRect(); return { x: 0, y: r.top - 12, width: 420, height: r.height + 24 }; }) });
await p.click('.acc-close'); await wait(300);
ok(await ev(() => !document.getElementById('menu').classList.contains('on') && document.activeElement === document.querySelector('#rail [data-go="account"]')), 'Close closes and returns focus');
console.log(fails ? `${fails} FAILED` : 'ALL PASS', '| errors', errs); await b.close();
