import { createRequire } from 'node:module'; import path from 'node:path'; import { pathToFileURL } from 'node:url';
const require = createRequire(import.meta.url); const puppeteer = require('puppeteer');
const b = await puppeteer.launch({ headless: true, args: ['--allow-file-access-from-files'] }); const p = await b.newPage();
const errs = []; p.on('pageerror', (e) => errs.push(e.message));
const url = pathToFileURL(path.resolve('index.html')).href, wait = (ms) => new Promise((r) => setTimeout(r, ms));
let fails = 0; const ok = (c, m) => { if (!c) fails++; console.log(c ? 'PASS' : 'FAIL', m); }; const ev = (f, ...a) => p.evaluate(f, ...a); const idle = () => p.evaluate(() => window.XENO_NET?.idle?.());
const nav = async (it) => { await p.goto(url + '#/overview/g/community' + (it ? '/' + it : '')); await p.reload(); await wait(900); await idle(); };
const click = (sel, txt) => ev((s, t) => { const n = [...document.querySelectorAll(s)].find((e) => !t || e.textContent.includes(t)); if (!n) throw new Error('no ' + s + ' ' + t); n.click(); }, sel, txt ?? null).then(() => wait(450)).then(idle);
const dlg = () => ev(() => [...document.querySelectorAll('.xd')].pop()?.textContent || '');
const submit = async () => { await ev(() => [...document.querySelectorAll('.xd')].pop().querySelector('[data-xd-submit], .xd-foot .xd-btn:not(.ghost)').click()); await wait(500); await idle(); };
const type = (id, v) => ev((i, x) => { const n = document.querySelector('#xdf-' + i); n.value = x; n.dispatchEvent(new Event('input', { bubbles: true })); }, id, v);
const pick = (f, v) => ev((f2, v2) => [...document.querySelectorAll(`.xd [data-f="${f2}"] [data-v]`)].find((x) => x.dataset.v === v2).click(), f, v);
const crumb = () => ev(() => document.querySelector('#main .crumbs b')?.textContent);
await p.setViewport({ width: 1440, height: 900 }); await p.goto(url);
await ev(() => { localStorage.clear(); localStorage.setItem('xw.introSeen', JSON.stringify({ studio: 1, office: 1, social: 1, corpo: 1, dev: 1, tools: 1 })); });
await nav(); await click('#main [data-pg-gitem="th_0"]'); let g = await ev(() => location.hash);
ok(/community\/th_0$/.test(g), `threads are addressed by a stable id, not their title (${g})`);
await nav('th_0'); ok(/export a Canvas frame/.test(await crumb()), 'and that address opens the thread after a refresh');
g = await ev(() => { const v = document.querySelector('#main .cm-vote'); return +v.querySelector('b').textContent; }); await click('#main .cm-vote');
let g2 = await ev(() => ({ n: +document.querySelector('#main .cm-vote b').textContent, on: document.querySelector('#main .cm-vote').getAttribute('aria-pressed') }));
ok(g2.n === g + 1 && g2.on === 'true', 'a person’s Helpful vote counts and can be taken back');
ok(await ev(() => !!document.querySelector('#main .cm-agents')), 'agents’ signals show separately and never add to the count (D6)');
await click('#main [data-cm="flag"]', 'Report'); ok(/moderators for review/.test(await dlg()), 'reporting a post goes to review'); await pick('w', 'spam'); await submit();
await nav('Moderation'); g = await ev(() => document.querySelectorAll('#main .cm-q').length); ok(g === 1, 'the report waits in the moderation queue');
await click('#main [data-cm="resolve"]', 'Lock thread'); g = await ev(() => document.querySelector('#main .cm-log li')?.textContent || ''); ok(/Locked/.test(g), `the action is written to the public moderation log (${g.slice(0, 60)})`);
await nav('th_0'); ok(await ev(() => !document.querySelector('#main .pg-reply') && /Locked/.test(document.querySelector('#main').textContent)), 'a locked thread stays readable and takes no replies');
// public report with duplicate detection → join
await nav(); await ev(() => { window.XA.report(); }); await wait(400); await type('title', 'Export Canvas frame SVG keeps live text?'); await submit();
ok(/may have reported this already/.test(await dlg()), 'a public report checks for duplicates before posting (D10)'); await submit();
g = await ev(() => JSON.parse(localStorage.getItem('xw.db.v1')).forum.find((t) => t.id === 'th_0').reporters); ok(g === 2, 'joining adds you as a second reporter instead of a new copy');
// private ticket → write-back
await ev(() => { window.XA.report(); }); await wait(400); await type('title', 'Library search ignores file names'); await pick('vis', 'private'); await submit(); await wait(300);
g = await crumb(); ok(/1041/.test(g || ''), `a private report opens its ticket page (${g})`);
await wait(2700); g = await ev(() => document.querySelector('#main .cm-steps li.on span')?.textContent); ok(g === 'Looked at', `and you see each step as the team works on it (${g})`);
await nav('My reports'); g = await ev(() => ({ fixed: !!document.querySelector('#main .mk-own.cm-new'), n: document.querySelectorAll('#main .mk-own').length }));
ok(g.fixed, 'a ticket fixed since you last looked is marked new, with the version it shipped in');
await click('#main [data-cm="ticket"]', '#1031'); ok(/Fixed in Canvas 0.39.2/.test(await ev(() => document.querySelector('#main').textContent)), 'the ticket says which version fixed it');
await click('#main [data-cm="publish"]'); await submit(); g = await ev(() => JSON.parse(localStorage.getItem('xw.db.v1')).forum[0]); ok(g.title.startsWith('Canvas freezes') && g.fixedIn === 'Canvas 0.39.2', 'you can make your own ticket public — it carries the fix with it (R4)');
await ev(() => document.dispatchEvent(new KeyboardEvent('keydown', { key: 'r', ctrlKey: true, altKey: true, bubbles: true }))); await wait(400); ok(/Report a problem/.test(await dlg()), 'Ctrl+Alt+R opens the report window too (R6)');
console.log(fails ? `${fails} FAILED` : 'ALL PASS', '| errors', errs.slice(0, 5)); await b.close();
