import { createRequire } from 'node:module'; import path from 'node:path'; import { pathToFileURL } from 'node:url';
const require = createRequire(import.meta.url); const puppeteer = require('puppeteer');
const b = await puppeteer.launch({ headless: true, args: ['--no-sandbox', '--allow-file-access-from-files'] }); const p = await b.newPage();
await p.setViewport({ width: 1440, height: 900 }); const errs = []; p.on('pageerror', (e) => errs.push(e.message));
const w = (ms) => new Promise((r) => setTimeout(r, ms)); const url = pathToFileURL(path.resolve('index.html')).href;
await p.goto(url); await p.evaluate(() => { try { localStorage.clear(); } catch {} });
const st = () => p.evaluate(() => ({ hash: location.hash, crumbs: document.querySelector('.crumbs')?.innerText.replace(/\s+/g, ' '), logo: document.querySelector('#logo')?.getAttribute('aria-label')?.split(' —')[0], ctx: document.querySelector('.ctx-note')?.textContent, firstChat: document.querySelector('#panel > .pv [data-chat]')?.dataset.chat }));
await p.goto(url + '#/overview'); await w(500);
await p.click('#rail [data-go="chat"]'); await w(500); console.log('overview -> chat:', JSON.stringify(await st()));
await p.goto(url + '#/studio'); await w(500);
await p.click('#rail [data-go="chat"]'); await w(500); console.log('studio -> chat:', JSON.stringify(await st()));
await p.goto(url + '#/overview'); await w(500);
await p.click('#panel > .pv [data-item-p="agent"]'); await w(500); console.log('overview needs-you -> item:', JSON.stringify(await st()));
await p.screenshot({ path: 'ctx-item.png', clip: { x: 0, y: 0, width: 1100, height: 600 } });
await p.goBack(); await w(500); console.log('back:', (await st()).hash);
await p.goto(url + '#/social/p/post'); await w(500);
await p.click('#panel > .pv [data-item="Calendar"]'); await w(500); console.log('post view:', JSON.stringify(await st()), 'marked:', await p.evaluate(() => document.querySelector('#panel > .pv [data-item="Calendar"]').getAttribute('aria-current')));
await p.reload(); await w(600); console.log('after reload:', (await st()).hash, (await st()).crumbs);
await p.click('[data-back]'); await w(400); console.log('back btn:', (await st()).hash);
await p.goto(url + '#/office/z/write'); await w(400); await p.click('#panel > .pv [data-item-p="docs"]'); await w(500); console.log('office zone item:', JSON.stringify(await st()));
console.log('errors', errs); await b.close();
