import { createRequire } from 'node:module'; import path from 'node:path'; import { pathToFileURL } from 'node:url';
const require = createRequire(import.meta.url); const puppeteer = require('puppeteer');
const b = await puppeteer.launch({ headless: true, args: ['--allow-file-access-from-files'] }); const p = await b.newPage();
const errs = []; p.on('pageerror', (e) => errs.push(e.message));
const url = pathToFileURL(path.resolve('index.html')).href, wait = (ms) => new Promise((r) => setTimeout(r, ms));
let fails = 0; const ok = (c, m) => { if (!c) fails++; console.log(c ? 'PASS' : 'FAIL', m); }; const ev = (f, ...a) => p.evaluate(f, ...a);
const F = () => ev(() => JSON.parse(localStorage.getItem('xw.funding'))['Brand refresh']);
const fd = (a, arg) => ev((x, y) => [...document.querySelectorAll('#main [data-fd]')].find((e) => e.dataset.fd === x && (y == null || e.dataset.arg === y)).click(), a, arg ?? null).then(() => wait(400));
const submit = async () => { await ev(() => [...document.querySelectorAll('.xd')].pop().querySelector('[data-xd-submit], .xd-foot .xd-btn:not(.ghost)').click()); await wait(450); };
await p.setViewport({ width: 1440, height: 900 }); await p.goto(url);
await ev(() => { localStorage.clear(); localStorage.setItem('xw.introSeen', JSON.stringify({ studio: 1, office: 1, social: 1, corpo: 1, dev: 1, tools: 1 })); localStorage.setItem('xw.workspace', '"xeno"'); });
const open = async () => { await p.goto(url + '#/studio/g/projects/Brand refresh/Funding'); await p.reload(); await wait(900); };
await open();
let g = await ev(() => ({ sums: [...document.querySelectorAll('#main .fd-sum small')].map((x) => x.textContent), ms: document.querySelectorAll('#main .fd-ms').length }));
console.log(JSON.stringify(g), await ev(()=>location.hash+' '+document.querySelector('#main').textContent.slice(0,150))); ok(g.sums.join() === 'Confirmed,Committed,Consumed,Returned,Disputed' && g.ms === 3, `contributor view shows the five states and three milestones (FUND-12)`);
g = await ev(() => document.querySelector('#main .fd-ms--locked')?.textContent || ''); ok(/Locked|Funded/.test(g), 'an unfunded milestone is locked (FUND-14)');
await fd('contribute', 'Brand refresh|m3'); g = await ev(() => [...document.querySelectorAll('.xd')].pop().textContent);
ok(/welcome credit can’t/.test(g) && /no membership/.test(g), 'contribute shows promo credit is ineligible and no membership is granted (FUND-02/15)');
await submit(); g = (await F()).contribs[0]; ok(g.state === 'pending', 'a new contribution is pending, not failed (FUND-05)');
await wait(1700); g = (await F()).contribs[0]; ok(g.state === 'confirmed' && g.milestone === 'm3', 'then confirms, restricted to its milestone');
await open(); await fd('cap', 'Brand refresh|Emilian|plan'); g = await ev(() => document.getElementById('toast').textContent);
ok(/can’t grant yourself/.test(g), 'you cannot grant yourself a right (FUND-13)');
const before = (await F()).contribs.find((c) => c.who === 'Emilian' && c.milestone === 'm3').amount;
await fd('return', (await F()).contribs[0] && `Brand refresh|${(await F()).contribs[0].id}`); await submit(); await wait(1500);
g = (await F()).contribs.find((c) => c.state === 'returned'); ok(g && g.amount === before, 'unspent value returns to its origin (FUND-10)');
console.log(fails ? `${fails} FAILED` : 'ALL PASS', '| errors', errs.slice(0, 5)); await b.close();
