import { createRequire } from 'node:module'; import path from 'node:path'; import { pathToFileURL } from 'node:url';
const require = createRequire(import.meta.url); const puppeteer = require('puppeteer');
const b = await puppeteer.launch({ headless: true, args: ['--allow-file-access-from-files'] }); const p = await b.newPage();
const errs = []; p.on('pageerror', (e) => errs.push(e.message));
const url = pathToFileURL(path.resolve('index.html')).href, wait = (ms) => new Promise((r) => setTimeout(r, ms));
let fails = 0; const ok = (c, m) => { if (!c) fails++; console.log(c ? 'PASS' : 'FAIL', m); }; const ev = (f, ...a) => p.evaluate(f, ...a);
const nav = async (it) => { await p.goto(url + '#/overview/g/market' + (it ? '/' + it : '')); await p.reload(); await wait(900); };
const click = (sel, txt) => ev((s, t) => { const n = [...document.querySelectorAll(s)].find((e) => !t || e.textContent.includes(t)); if (!n) throw new Error('no ' + s + ' ' + t); n.click(); }, sel, txt ?? null).then(() => wait(450));
const submit = async () => { await ev(() => [...document.querySelectorAll('.xd')].pop().querySelector('[data-xd-submit], .xd-foot .xd-btn:not(.ghost)').click()); await wait(500); };
const E = () => ev(() => JSON.parse(localStorage.getItem('xw.mkEnts') || '{}'));
await p.setViewport({ width: 1440, height: 900 }); await p.goto(url);
await ev(() => { localStorage.clear(); localStorage.setItem('xw.introSeen', JSON.stringify({ studio: 1, office: 1, social: 1, corpo: 1, dev: 1, tools: 1 })); });
await nav(); await click('#main [data-mk="open"]', 'Brand checker');
let g = await ev(() => ({ h: location.hash, t: document.querySelector('#main .crumbs b')?.textContent, caps: document.querySelectorAll('#main .mk-caps li').length, revs: document.querySelectorAll('#main .mk-revs li').length, note: document.querySelector('#main')?.textContent.includes('Only people who have it can review it') }));
ok(g.t === 'Brand checker' && /Brand%20checker/.test(g.h), `a card opens its own listing page with a real link (${g.h})`);
ok(g.caps > 0 && g.revs > 0 && g.note, 'the page shows what it may do, reviews, and that only owners can review');
await p.reload(); await wait(900); ok(await ev(() => document.querySelector('#main .crumbs b')?.textContent) === 'Brand checker', 'the listing link survives a refresh');
await click('#main [data-xa="getListing"]'); await submit(); g = await E();
ok(g.lst_1?.model === 'subscription' && g.lst_1.state === 'active', 'subscribing creates an entitlement with its terms');
g = await ev(() => document.querySelector('#main .mk-ent')?.textContent || ''); ok(/Renews/.test(g), 'the listing now shows what you have and when it renews');
await click('#main [data-mk="cancel"]'); await submit(); g = await E(); ok(g.lst_1.state === 'cancelled', 'cancel keeps it until the paid month ends');
await click('#main [data-mk="review"]'); await ev(() => { const t = document.querySelector('.xd textarea'); t.value = 'Catches off-brand fonts fast'; t.dispatchEvent(new Event('input', { bubbles: true })); }); await submit();
g = await ev(() => [...document.querySelectorAll('#main .mk-revs li b')].map((x) => x.textContent)); ok(g.includes('You'), 'an owner can post a review');
await nav('SaaS onboarding blueprint'); await click('#main [data-xa="getListing"]'); await submit();
await click('#main [data-mk="refund"]'); await submit(); g = await E(); ok(g.lst_4.state === 'refunded', 'an unopened purchase refunds inside its window');
await nav('Bookkeeper'); g = await ev(() => document.querySelector('#main')?.textContent.includes('private memory is never loaded')); ok(g, 'the listing states the memory rules before you rent (M3)');
await click('#main [data-xa="getListing"]'); await submit(); g = await ev(() => document.querySelector('#main .mk-part')?.textContent || '');
ok(/Your memory with it/.test(g), 'renting a Mind gives you your own memory with it — exportable and deletable (M2/M4)');
await nav('Rentals'); g = await ev(() => [...document.querySelectorAll('#main .mk-own b')].map((x) => x.textContent)); ok(g.some((x) => /Bookkeeper/.test(x)), `Rentals lists entitlements, not catalog cards (${g.join(', ')})`);
await nav('Seller console'); g = await ev(() => ({ sums: [...document.querySelectorAll('#main .fd-sum small')].map((x) => x.textContent), live: document.querySelectorAll('#main .mk-sl').length }));
ok(g.sums.join() === 'Earned,On hold,Ready to pay out,Paid out' && g.live >= 1, 'the console shows earnings with fee and hold, and your listings');
ok(await ev(() => !document.querySelector('#main [data-mk="payout"]')), 'no payout before the company is verified');
await click('#main [data-mk="soul"]'); g = await ev(() => [...document.querySelectorAll('.xd')].pop().textContent); ok(/never loaded/.test(g), 'the Soul review decides what renters’ runs may use (M1)'); await submit();
await click('#main [data-mk="kyb"]'); await ev(() => { for (const id of ['n', 'r']) { const i = document.querySelector('#xdf-' + id); i.value = 'XENO FZ-LLC'; i.dispatchEvent(new Event('input', { bubbles: true })); } [...document.querySelectorAll('.xd [data-f="c"] [data-v]')][0].click(); }); await submit(); await wait(2800);
await click('#main [data-mk="payout"]'); await submit(); g = await ev(() => JSON.parse(localStorage.getItem('xw.mkSeller')).payouts.length); ok(g === 1, 'once verified, the available balance pays out');
await click('#main [data-xa="newListing"]'); await ev(() => { for (const id of ['name', 'blurb']) { const i = document.querySelector('#xdf-' + id); i.value = 'Swatch tool'; i.dispatchEvent(new Event('input', { bubbles: true })); } }); await submit();
g = await ev(() => document.querySelector('#main .mk-checks')?.textContent || ''); ok(/Signature matches/.test(g), 'a submission shows the checks it is going through');
await wait(3300); g = await ev(() => JSON.parse(localStorage.getItem('xw.db.v1')).market.find((x) => x.name === 'Swatch tool').review); ok(g === 'live', `and goes live when they pass (${g})`);
console.log(fails ? `${fails} FAILED` : 'ALL PASS', '| errors', errs.slice(0, 5)); await b.close();
