import { createRequire } from 'node:module'; import path from 'node:path'; import { pathToFileURL } from 'node:url';
const require = createRequire(import.meta.url); const puppeteer = require('puppeteer');
const b = await puppeteer.launch({ headless: true, args: ['--allow-file-access-from-files'], protocolTimeout: 60000 }); const p = await b.newPage();
const errs = []; p.on('pageerror', (e) => errs.push(e.message));
const url = pathToFileURL(path.resolve('index.html')).href, wait = (ms) => new Promise((r) => setTimeout(r, ms));
let fails = 0; const ok = (c, m) => { if (!c) fails++; console.log(c ? 'PASS' : 'FAIL', m); }; const ev = (f, ...a) => p.evaluate(f, ...a);
await p.setViewport({ width: 1440, height: 900 }); await p.goto(url);
await ev(() => { localStorage.clear(); localStorage.setItem('xw.introSeen', JSON.stringify({ studio: 1, office: 1, social: 1, corpo: 1, dev: 1, tools: 1 })); localStorage.setItem('xw.workspace', '"xeno"'); });
await p.goto(url + '#/overview'); await p.reload(); await wait(900);
const q = async (s) => { await ev(() => window.XW.search('')); await wait(200); await ev((v) => { const i = document.querySelector('#palette input'); i.value = v; i.dispatchEvent(new Event('input')); }, s); await wait(200); return ev(() => [...document.querySelectorAll('#palette .row[data-pi]')].map((r) => ({ t: r.querySelector('.t').textContent, g: r.previousElementSibling?.classList.contains('grp') ? r.previousElementSibling.textContent : null }))); };
const groups = () => ev(() => [...document.querySelectorAll('#palette .grp')].map((g) => g.textContent));
const enter = async () => { await ev(() => document.querySelector('#palette input').dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true }))); await wait(700); };
let r = await q('password'); ok(r[0]?.t === 'Sign-in & security', `Settings are found by the words people use ("password" → ${r[0]?.t})`);
await enter(); ok(/settings/.test(await ev(() => location.hash)), 'Enter opens that settings section');
r = await q('brand'); let gs = await groups(); ok(gs.includes('Projects') && gs.includes('Marketplace'), `one query reaches several kinds (${gs.join(', ')})`);
r = await q('atlas'); ok(r.some((x) => x.t === 'Atlas'), 'agents and Minds are found by name');
r = await q('vat'); ok(r[0]?.t === 'Company', `the company page is found by what it holds ("vat" → ${r[0]?.t})`);
r = await q('cnvs frm'); r = await q('xprt'); ok(r.length > 0, `fuzzy: letters in order still match ("xprt" → ${r[0]?.t})`);
r = await q('freezes'); ok(r.some((x) => /#1031/.test(x.t)), 'your private tickets are searchable for you');
r = await q('>'); gs = await groups(); ok(gs.length === 1 && gs[0] === 'Commands' && r.some((x) => x.t === 'New project'), 'typing > lists commands');
r = await q('>report'); ok(r[0]?.t === 'Report a problem', 'commands filter too'); await enter(); ok(/Report a problem/.test(await ev(() => [...document.querySelectorAll('.xd')].pop()?.textContent || '')), 'and run'); await ev(() => document.querySelector('.xd [data-xd-cancel], .xd .xd-btn.ghost')?.click()); await wait(300);
r = await q('juno'); await enter(); r = await q(''); gs = await groups(); ok(gs[0] === 'Recent' && r[0]?.t === 'Juno', `an empty search starts with what you opened recently (${r[0]?.t})`);
r = await q('memo'); const per = {}; r.forEach((x, i, a) => { }); ok(r.length <= 18, 'results stay bounded');
r = await q('zzqqxx'); ok(await ev(() => /No results/.test(document.querySelector('#palette .res').textContent)), 'no match says so');
console.log(fails ? `${fails} FAILED` : 'ALL PASS', '| errors', errs.slice(0, 5)); await b.close();
