import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';

const root = new URL('../', import.meta.url);
const manifest = JSON.parse(readFileSync(new URL('compliance/generated-assets-2026-09-04.json', root), 'utf8'));

test('every generated replacement retains its exact prompt and byte-level provenance', () => {
  assert.equal(manifest.entries.length, 8);
  assert.equal(new Set(manifest.entries.map(e => e.path)).size, 8);
  for (const entry of manifest.entries) {
    assert.match(entry.path, /^public\/landing-v3\/(?:usecases\/)?[a-z-]+\.png$/);
    const data = readFileSync(new URL(entry.path, root));
    assert.equal(data.subarray(0, 8).toString('hex'), '89504e470d0a1a0a');
    assert.equal(createHash('sha256').update(data).digest('hex'), entry.sha256, entry.path);
    assert.match(entry.prompt, /Use case:/);
    assert.match(entry.generator, /image_gen built-in/);
    assert.deepEqual(entry.referenceImages, []);
    assert.match(entry.usage, /not a screenshot/);
  }
});

test('generation records never claim to clear unrelated assets or establish legal signoff', () => {
  assert.equal(manifest.status, 'generation-evidence-recorded-not-legal-signoff');
  assert.ok(manifest.entries.every(e => !/logo|favicon|demo/.test(e.path)));
});

test('asset registry covers only exact generated bytes with traceable origin and rights evidence', () => {
  const registry = JSON.parse(readFileSync(new URL('compliance/assets.json', root), 'utf8'));
  assert.equal(registry.entries.length, manifest.entries.length);
  assert.deepEqual(registry.entries.map(e => e.path).sort(), manifest.entries.map(e => e.path).sort());
  for (const entry of registry.entries) {
    assert.doesNotMatch(entry.path, /[\*?\[\]\\]|(?:^|\/)\.\.(?:\/|$)/);
    assert.equal(entry.origin, 'ai-generated');
    assert.equal(entry.evidence, 'compliance/generated-assets-2026-09-04.json');
    assert.equal(entry.sha256, manifest.entries.find(e => e.path === entry.path).sha256);
    assert.equal(createHash('sha256').update(readFileSync(new URL(entry.path, root))).digest('hex'), entry.sha256);
    assert.equal(entry.rightsEvidence, 'docs/release-evidence/openai-output-rights-basis-2026-09-05.md');
    const rights = readFileSync(new URL(entry.rightsEvidence, root), 'utf8');
    assert.match(rights, /https:\/\/openai\.com\/policies\/eu-terms-of-use\//);
    assert.match(rights, /https:\/\/openai\.com\/policies\/services-agreement\//);
    assert.match(rights, /not a warranty/);
    assert.equal(entry.signed_off_by, undefined);
    assert.equal(entry.disposition, undefined);
  }
  assert.match(registry.scope, /Other assets remain undeclared/);
});

test('use-case backgrounds share a neutral loading fallback', () => {
  const source = readFileSync(new URL('src/components/landing-v3/UseCasesSection.tsx', root), 'utf8');
  assert.match(source, /linear-gradient\(165deg, #191919, #070707 72%\)/);
  assert.doesNotMatch(source, /p\.fallback|rgba\(170,140,255/);
});

test('product video generation never substitutes a stock clip for a provider result', () => {
  const source = readFileSync(new URL('src/components/playground/Generation/VideoGenerationInterface2.tsx', root), 'utf8');
  assert.doesNotMatch(source, /DEMO_MOCK_GENERATION|DEMO_SAMPLE_VIDEOS|mockVideos|gtv-videos-bucket/);
  assert.match(source, /await videoGenerationService\.generateVideo\(selectedModel, settings\)/);
  assert.match(source, /No video was generated/);
});
