import type { ProductDocs } from './_types';

const body = (...lines: string[]): string => lines.join('\n');

const acp: ProductDocs = {
  slug: 'acp',
  productName: 'XENO ACP',
  tagline: 'One protocol for approved coding agents — embedded, behind an OpenAI-compatible gateway, or inside XENO Hub.',
  seo: {
    title: 'XENO ACP 0.1.1 documentation',
    description: 'Install and operate the XENO ACP client engine, OpenAI-compatible gateway, provider runtime, and XENO Hub integration on Windows and Linux.',
  },
  sections: [
    {
      title: 'Getting started',
      pages: [
        {
          slug: 'introduction',
          title: 'Introduction',
          description: 'What ships in XENO ACP 0.1.1, where it fits, and the exact public-beta support boundary.',
          body: body(
            '# Introduction',
            '',
            '**XENO ACP** is the XENO ecosystem’s shared implementation of the [Agent Client Protocol](https://agentclientprotocol.com) boundary. It can drive configured ACP agents, expose them through an OpenAI-compatible local HTTP API, run a XENO-owned ACP agent endpoint, and provide the provider policy domain consumed by XENO Hub.',
            '',
            '> ACP is to coding agents what LSP is to language servers: one wire protocol lets a client drive different conforming agents. XENO ACP is primarily an ACP **client and gateway**; it also ships a deliberately narrower ACP **agent-side endpoint**.',
            '',
            '## Packages',
            '',
            '| Package | Purpose |',
            '|---|---|',
            '| `@xenosystem/acp` | OpenAI-compatible local gateway and `xeno-acp` CLI |',
            '| `@xenosystem/acp-core` | Framework-free ACP client engine and structured event stream |',
            '| `@xenosystem/acp-agent` | XENO-owned ACP stdio endpoint and approval-gated local adapter runtime |',
            '| `@xenosystem/acp-provider-manager` | Provider catalog, lifecycle, certification and safe update policy |',
            '',
            '## Public-beta status',
            '',
            '**Version 0.1.1 is product-ready for the documented trusted-local Windows and Linux scope.** The exact package candidate passed clean install, import, CLI, checksum, reproducibility and product-ready gates on Windows and Ubuntu/Linux. The same packages were exercised through the XENO Hub agent interface, including a packaged Electron launch.',
            '',
            'The claim is intentionally narrow:',
            '',
            '- macOS is not claimed in 0.1.1;',
            '- local provider wrappers use your installed and authenticated third-party CLI; they are not official provider-owned ACP implementations;',
            '- the separate-process supervisor is a lifecycle boundary, not hostile-code network or filesystem containment;',
            '- XENO ACP does not pool, extract, proxy or resell provider credentials.',
            '',
            '## Next steps',
            '',
            '- [Installation](/docs/acp/installation) — install the public packages',
            '- [Quickstart](/docs/acp/quickstart) — start the gateway and send a turn',
            '- [Safety and sandboxing](/docs/acp/safety-and-sandboxing) — understand the trust boundary before enabling a provider',
          ),
        },
        {
          slug: 'installation',
          title: 'Installation',
          description: 'Install the public npm packages on a supported platform and initialize a local gateway configuration.',
          body: body(
            '# Installation',
            '',
            '## Requirements',
            '',
            '- **Windows or Linux** — the validated 0.1.1 targets',
            '- **Node.js 20 or newer**',
            '- A provider’s own installed and authenticated CLI when you choose a live provider path',
            '',
            '## Gateway CLI',
            '',
            'Install the OpenAI-compatible gateway globally:',
            '',
            '```bash',
            'npm install --global @xenosystem/acp',
            'xeno-acp --version',
            'xeno-acp init',
            '```',
            '',
            '`xeno-acp init` creates `xeno-acp.config.jsonc` in the current directory without reading provider credentials. Review the generated agents and local bearer keys, then start the gateway:',
            '',
            '```bash',
            'xeno-acp --config ./xeno-acp.config.jsonc',
            '```',
            '',
            'The default listen address is `http://127.0.0.1:8787`.',
            '',
            '## Embeddable packages',
            '',
            'Install only the surfaces your application needs:',
            '',
            '```bash',
            'npm install @xenosystem/acp-core',
            'npm install @xenosystem/acp-provider-manager',
            'npm install @xenosystem/acp-agent',
            '```',
            '',
            'Use `xeno-acp-core` for structured ACP client events. Hosts such as XENO Hub use `xeno-acp-provider-manager` as the provider decision boundary and supply their own platform I/O and UI. Install `xeno-acp-agent` when another ACP client needs to spawn the XENO-owned stdio endpoint.',
            '',
            '## Source development',
            '',
            '```bash',
            'git clone https://github.com/XENO-CORPORATION/xeno-acp',
            'cd xeno-acp',
            'pnpm install --frozen-lockfile',
            'pnpm run quality',
            'pnpm run smoke',
            '```',
            '',
            'The automated tests are hermetic: they drive fixtures, not your installed provider CLIs or credentials.',
          ),
        },
        {
          slug: 'quickstart',
          title: 'Quickstart',
          description: 'Initialize the local gateway, list configured agents, stream a turn, or embed the structured client engine.',
          body: body(
            '# Quickstart',
            '',
            '## 1. Install and initialize',
            '',
            '```bash',
            'npm install --global @xenosystem/acp',
            'xeno-acp init',
            '```',
            '',
            'Edit `xeno-acp.config.jsonc` to enable the ACP agents and local bearer keys you want. Each live provider must already be installed and authenticated through its own supported flow.',
            '',
            '## 2. Start the gateway',
            '',
            '```bash',
            'xeno-acp --config ./xeno-acp.config.jsonc',
            '```',
            '',
            '## 3. List configured agents',
            '',
            '```bash',
            'curl -s http://127.0.0.1:8787/v1/models \\',
            '  -H "authorization: Bearer dev-key"',
            '```',
            '',
            'Use an id returned by `/v1/models` as the request `model`.',
            '',
            '## 4. Stream a turn',
            '',
            '```bash',
            'curl -N http://127.0.0.1:8787/v1/chat/completions \\',
            '  -H "authorization: Bearer dev-key" \\',
            '  -H "content-type: application/json" \\',
            '  -d \'{"model":"<model-id>","stream":true,"messages":[{"role":"user","content":"Summarize this workspace."}]}\'',
            '```',
            '',
            'The response is an OpenAI-compatible SSE stream ending in `data: [DONE]`. Add `"xeno":{"verbose":true}` when you want tool and plan narration in the text stream.',
            '',
            '## Embed instead of serving HTTP',
            '',
            '```bash',
            'npm install @xenosystem/acp-core',
            '```',
            '',
            '```ts',
            'import { AcpManager, loadConfig } from "@xenosystem/acp-core";',
            '',
            'const acp = new AcpManager(await loadConfig());',
            'try {',
            '  for await (const event of acp.prompt("claude-code", {',
            '    messages: [{ role: "user", content: "Summarize this workspace." }],',
            '  })) {',
            '    if (event.type === "text") process.stdout.write(event.text);',
            '  }',
            '} finally {',
            '  await acp.dispose();',
            '}',
            '```',
          ),
        },
      ],
    },
    {
      title: 'Core concepts',
      pages: [
        {
          slug: 'architecture',
          title: 'Architecture',
          description: 'The client engine, HTTP gateway, agent endpoint, provider policy package, and XENO Hub host boundary.',
          body: body(
            '# Architecture',
            '',
            'XENO ACP separates wire protocol, HTTP translation, provider policy and host UI so each layer can be tested and consumed independently.',
            '',
            '```text',
            'XENO Hub / application',
            '  ├─ @xenosystem/acp-provider-manager  (catalog + lifecycle + policy)',
            '  └─ @xenosystem/acp-core              (ACP client + structured events)',
            '',
            '@xenosystem/acp                         (OpenAI-compatible HTTP)',
            '  └─ @xenosystem/acp-core',
            '       └─ @agentclientprotocol/sdk                  (ACP v1 over stdio)',
            '',
            'External ACP client',
            '  └─ @xenosystem/acp-agent               (XENO-owned ACP endpoint)',
            '```',
            '',
            '## Core client engine',
            '',
            '`AcpManager` owns configured agent processes, concurrency limits and prompt turns. `AgentProcess` handles stdio and the ACP initialize handshake. Each request creates an ephemeral ACP session and emits a typed `AcpEvent` stream. Filesystem, terminal and permission callbacks are handled inside the session workspace.',
            '',
            '## HTTP gateway',
            '',
            'The gateway translates an OpenAI-style request into a core prompt and flattens structured ACP updates into text or SSE. The reserved `xeno.session` field is accepted in 0.1.1, but requests remain ephemeral and the complete conversation is rendered into the turn.',
            '',
            '## Agent endpoint and provider manager',
            '',
            'The agent endpoint is the inverse wire role: another ACP client can spawn it over stdio. Its local providers are resolved through definition, policy, implementation and approval gates. The provider-manager package exposes that domain to hosts without giving it Electron, filesystem or network authority.',
            '',
            '## XENO Hub integration',
            '',
            'XENO Hub supplies platform bridges and UI projections around the published core and provider-manager contracts. Provider catalog, model discovery, approval, certification, diagnostics, support bundle and session state remain typed IPC surfaces; provider policy is not reimplemented in the renderer.',
          ),
        },
        {
          slug: 'agents-and-auth',
          title: 'Agents and authentication',
          description: 'Client-side ACP definitions, agent-side local adapters, approvals, and the bring-your-own-login scope.',
          body: body(
            '# Agents and authentication',
            '',
            'There are two distinct provider surfaces. Do not merge their claims.',
            '',
            '## ACP client agents',
            '',
            'The core gateway treats an ACP agent as configuration. Built-in definitions cover these launch shapes:',
            '',
            '| id | Default launch | Kind |',
            '|---|---|---|',
            '| `claude-code` | `npx -y @zed-industries/claude-code-acp` | ACP adapter |',
            '| `codex` | `npx -y @zed-industries/codex-acp` | ACP adapter |',
            '| `opencode` | `opencode acp` | native ACP |',
            '| `gemini` | `gemini --acp` | native ACP |',
            '| `kimi` | `kimi acp` | native ACP |',
            '| `glm` | `npx -y glm-acp-agent@latest` | ACP package |',
            '',
            'A custom conforming ACP agent can be added in configuration. The operator is responsible for installing the command, reviewing its provenance, and authenticating through that provider’s own supported flow.',
            '',
            '## Agent-side local providers',
            '',
            '`@xenosystem/acp-agent` has a narrower registry:',
            '',
            '- `fixture` — deterministic, zero-I/O, used for certification and tests;',
            '- `xeno-local` — XENO-owned deterministic adapter, approval-gated;',
            '- `claude-local` — XENO-authored wrapper around an installed Claude Code CLI, approval-gated;',
            '- `codex-local` — XENO-authored wrapper around an installed Codex CLI in read-only sandbox mode, approval-gated.',
            '',
            'The base `codex`, `claude`, `gemini`, `opencode`, `kimi`, `glm` and `hermes` entries on the **agent side** remain disabled placeholders. An approval cannot make an unimplemented provider runnable.',
            '',
            '## Approval flow',
            '',
            '```bash',
            'xeno-acp-agent providers setup --provider <id>',
            'xeno-acp-agent providers review --provider <id>',
            'xeno-acp-agent providers secrets --provider <id>',
            'xeno-acp-agent providers approve --provider <id> --yes',
            'xeno-acp-agent providers test --provider <id>',
            '```',
            '',
            'Approvals are pinned to a hash of the provider definition and policy. Missing or stale approvals fail closed. Approval records contain hashes and metadata, never secret values.',
            '',
            '## Credential boundary',
            '',
            'XENO ACP does not perform provider OAuth, read provider credential files, extract subscription tokens, or proxy credentials. Live providers use the operator’s own installed and authenticated CLI. This is a trusted-local, single-owner surface — not multi-tenant credential sharing or resale.',
          ),
        },
        {
          slug: 'safety-and-sandboxing',
          title: 'Safety and sandboxing',
          description: 'What 0.1.1 contains, what its process supervisor enforces, and what remains outside the claim.',
          body: body(
            '# Safety and sandboxing',
            '',
            'XENO ACP has multiple safety boundaries with different strengths. The 0.1.1 public-beta claim depends on keeping them distinct.',
            '',
            '## ACP client callback containment',
            '',
            'Filesystem and terminal callbacks implemented by `@xenosystem/acp-core` are rooted in the session workspace. Path traversal, outside absolute paths and symlink escapes are rejected. Commands run with an explicit workspace `cwd`, configured timeouts and no `shell:true` launch.',
            '',
            'This contains authority exercised **through those ACP callbacks**. It does not automatically contain everything a separate provider process can do with the operator’s OS identity.',
            '',
            '## Cooperative provider sandbox',
            '',
            'XENO-authored adapters receive a deny-by-default `ProviderSandboxContext`. Network, secret, filesystem and terminal capabilities require policy grants and emit audit events. Context creation fails closed for a provider that is not runnable.',
            '',
            'This is an in-process dependency-injection boundary for cooperative XENO-authored code. It is not a hostile-code OS sandbox.',
            '',
            '## Separate-process supervisor',
            '',
            'The provider process supervisor enforces:',
            '',
            '- no-shell launch and an explicit executable;',
            '- a clean environment allowlist;',
            '- an absolute working directory;',
            '- hard timeout and best-effort process-tree cleanup;',
            '- bounded, redacted output capture and audit events.',
            '',
            'Its fixed enforcement labels are:',
            '',
            '```text',
            'processTreeKill: best_effort',
            'network: not_enforced',
            'filesystem: not_enforced_against_hostile_process',
            '```',
            '',
            'Use only provider processes you trust to run locally. Version 0.1.1 does not ship an OS/container sandbox, firewall enforcement, hostile-process filesystem policy, or macOS validation.',
            '',
            '## Local gateway scope',
            '',
            'The gateway defaults to localhost. Bearer keys are stored as plaintext in the local config and are suitable only for this trusted-local, single-owner scope. Do not expose an `open`-auth gateway to an untrusted network.',
            '',
            '## Verification',
            '',
            'Automated suites use deterministic fixtures and mocks. They do not invoke real provider CLIs, read operator config, load credentials, make provider network calls, or claim third-party certification.',
          ),
        },
      ],
    },
    {
      title: 'Reference',
      pages: [
        {
          slug: 'http-gateway',
          title: 'HTTP gateway',
          description: 'OpenAI-compatible endpoints, authentication, the xeno extension, flattening, and ephemeral-session behavior.',
          body: body(
            '# HTTP gateway',
            '',
            '`@xenosystem/acp` is a local OpenAI-compatible HTTP shell over `@xenosystem/acp-core`. Its default listen address is `http://127.0.0.1:8787`.',
            '',
            '## Endpoints',
            '',
            '### `GET /v1/models`',
            '',
            'Lists enabled agent definitions as OpenAI model objects. Use a returned `id` as the completion request model.',
            '',
            '### `POST /v1/chat/completions`',
            '',
            '| Field | 0.1.1 behavior |',
            '|---|---|',
            '| `model` | configured agent id, optionally `agent:submodel` |',
            '| `messages` | OpenAI-style messages rendered into the ACP turn |',
            '| `stream` | `true` for SSE; `false` for one completion object |',
            '| `xeno` | additive XENO controls |',
            '',
            'A streaming response uses `chat.completion.chunk` objects and ends with `data: [DONE]`.',
            '',
            '### `GET /healthz`',
            '',
            'Returns liveness, configured-agent process status and a non-secret server summary. It does not return bearer keys, environment values or workspace paths.',
            '',
            '## Authentication',
            '',
            'Send `Authorization: Bearer <key>`. Each configured key has an app label, agent allowlist and optional concurrency limit. Unknown keys are rejected in `bearer` mode. `open` mode is for local development only.',
            '',
            '## XENO extension',
            '',
            '```json',
            '{',
            '  "session": "app:thread-123",',
            '  "workspace": "/absolute/workspace/path",',
            '  "verbose": true,',
            '  "mode": "code"',
            '}',
            '```',
            '',
            '`session` is reserved in 0.1.1. Every gateway request still creates an ephemeral ACP session and renders the complete message history into the turn. `workspace` selects the bounded workspace, `verbose` narrates tool/plan/thought updates, and `mode` requests an advertised ACP session mode.',
            '',
            '## Flattening',
            '',
            '| ACP update | Default | `verbose:true` |',
            '|---|---|---|',
            '| agent message chunk | text delta | text delta |',
            '| thought chunk | omitted | narrated |',
            '| tool call / update | omitted | narrated |',
            '| plan / plan update | omitted | narrated |',
            '| usage update | final usage | final usage |',
            '',
            'Flattening changes presentation only. It does not disable the agent’s configured tools.',
          ),
        },
        {
          slug: 'embed-api',
          title: 'Embedding API',
          description: 'Drive configured ACP agents in-process with @xenosystem/acp-core and consume typed events.',
          body: body(
            '# Embedding API',
            '',
            'Install the framework-free engine:',
            '',
            '```bash',
            'npm install @xenosystem/acp-core',
            '```',
            '',
            '## Create a manager',
            '',
            '```ts',
            'import { AcpManager, loadConfig } from "@xenosystem/acp-core";',
            '',
            'const manager = new AcpManager(await loadConfig());',
            '```',
            '',
            '## Main methods',
            '',
            '- `prompt(agentId, options)` — async-iterate a structured turn;',
            '- `complete(agentId, options)` — collect final text, stop reason and usage;',
            '- `listAgents()` / `getAgentDef(id)` — inspect configured agents;',
            '- `statuses()` — inspect process and active-session state;',
            '- `dispose()` — cancel active work and stop processes.',
            '',
            '## Prompt options',
            '',
            '```ts',
            'interface PromptOptions {',
            '  messages: ChatMessage[];',
            '  session?: string;     // reserved; turns are ephemeral in 0.1.1',
            '  workspace?: string;',
            '  model?: string | null;',
            '  mode?: string;',
            '  verbose?: boolean;',
            '  signal?: AbortSignal;',
            '}',
            '```',
            '',
            '## Event stream',
            '',
            'The discriminated `AcpEvent` union includes `text`, `thought`, `tool_call`, `tool_update`, `plan`, `usage`, `raw`, `done` and `error`. Embedders receive these events directly; the HTTP gateway passes the same stream through `flatten()`.',
            '',
            '```ts',
            'for await (const event of manager.prompt("claude-code", {',
            '  messages: [{ role: "user", content: "Run the checks and summarize the result." }],',
            '})) {',
            '  switch (event.type) {',
            '    case "text": process.stdout.write(event.text); break;',
            '    case "tool_call": console.log(event.title, event.status); break;',
            '    case "plan": console.log(event.entries); break;',
            '    case "error": console.error(event.message); break;',
            '  }',
            '}',
            '```',
          ),
        },
        {
          slug: 'agent-endpoint',
          title: 'Agent endpoint',
          description: 'Operate the XENO-owned ACP stdio endpoint, review providers, and preserve the approval and process boundaries.',
          body: body(
            '# Agent endpoint',
            '',
            '`@xenosystem/acp-agent` is the inverse of the client engine: an external ACP client can spawn the `xeno-acp-agent` binary and communicate over JSON-RPC stdio.',
            '',
            '```bash',
            'npm install --global @xenosystem/acp-agent',
            'xeno-acp-agent --version',
            'xeno-acp-agent check',
            'xeno-acp-agent agent --provider fixture',
            '```',
            '',
            'In `agent` mode, stdout is ACP JSON-RPC only; diagnostics go to stderr.',
            '',
            '## Operator commands',
            '',
            '```text',
            'check | doctor | support-bundle | process check',
            'certify --provider <id>',
            'providers list | check | approvals',
            'providers setup | review | models | secrets | diagnose | test --provider <id>',
            'providers approve --provider <id> (--yes | --dry-run | --interactive)',
            'providers revoke --provider <id> --yes',
            'agent --provider <id>',
            '```',
            '',
            '`certify` is a local preflight and does not itself grant a Hub certification. `support-bundle` is metadata-only and redacted. Diagnostics never print secret values.',
            '',
            '## Runnability',
            '',
            'A provider is runnable only when its definition, implementation, policy and current hash-pinned approval agree. Missing/stale approval, blocked policy, unsupported runtime contract or unimplemented provider fails closed.',
            '',
            'The deterministic `fixture` is always available for protocol smoke. `xeno-local`, `claude-local` and `codex-local` are separate approval-gated paths with separate classifications. The latter two are XENO-authored wrappers around local third-party CLIs, not official provider ACP implementations.',
            '',
            '## Process boundary',
            '',
            'The minimal supervisor provides no-shell launch, environment allowlisting, absolute cwd, timeout, bounded/redacted capture and best-effort cleanup. It does not enforce network or filesystem containment against a hostile provider process. Review [Safety and sandboxing](/docs/acp/safety-and-sandboxing) before enabling a live provider.',
            '',
            '## XENO Hub',
            '',
            'XENO Hub consumes the provider manager and ACP client contracts through typed main-process services and IPC. The agent interface exposes catalog, model discovery, setup, approval/revocation, certification, diagnostics, support bundle and live session state while keeping provider execution and policy outside the renderer.',
          ),
        },
      ],
    },
  ],
};

export default acp;
