import type { ProductDocs } from './_types';

const md = (...lines: string[]): string => lines.join('\n');

const agent: ProductDocs = {
  slug: 'agent',
  productName: 'XENO Agent',
  tagline: 'The canonical graphical agent workspace — Chat, project-aware Agent mode, durable sessions, tools, terminals, coordination, and nested agents.',
  version: '0.3.16',
  updated: '2026-09-02',
  seo: {
    title: 'XENO Agent 0.3.16 documentation',
    description: 'Install and use XENO Agent: Chat, cited public-web Research, project-aware Agent mode, durable sessions, tools, coordination, ACP providers, and the ADE workbench.',
  },
  sections: [
    {
      title: 'Getting started',
      pages: [
        {
          slug: 'introduction',
          title: 'Introduction',
          description: 'What XENO Agent is, the surfaces it powers, and the boundaries of the experimental release.',
          body: md(
            '# XENO Agent',
            '',
            'XENO Agent is the graphical workspace for conversational and agentic work. The standalone desktop app, the Agent surface inside XENO Hub, and embeddable consumers use the same interface and Host contract rather than separate implementations.',
            '',
            'Use **Chat** for conversation without granting a project. Use **Agent** when the session should read, edit, run, review, and coordinate work inside an explicitly selected folder. Both modes use the same durable session model and provider catalog.',
            '',
            '## What ships',
            '',
            '- Streaming conversations and compact tool-call rendering.',
            '- Chat and Agent authority modes with visible workspace state.',
            '- Files, editor, terminal, review, checkpoints, policies, plugins/MCP, and provider controls where the selected host reports those capabilities.',
            '- Durable conversation tabs, recovery, Goal/Loop/Handoff state, and navigable nested agents.',
            '- ACP, SDK-native, and XENO Cloud execution lanes selected from live host descriptors.',
            '- A signed `agent@1` runtime surface that compatible Hub versions can update independently of the Hub installer.',
            '',
            '## Release boundary',
            '',
            'Version 0.3.16 is the standalone product release and 0.1.24 is the matching public Agent Interface package/runtime set. The 0.1.24 runtime fixes published Monaco worker resolution in Hub and other Vite consumers while retaining the `agent@1` contract. Hosted XENO Chat uses that shared interface contract. The desktop is an experimental Windows and Linux release: real distributable software, but not GA. Signing/notarization, macOS distribution, and portions of the cross-platform containment and deep-harness certification matrix remain separate admission gates. The interface reports actual capabilities instead of silently simulating unsupported ones.',
            '',
            'Next: [Install XENO Agent](/docs/agent/installation) or learn [Chat and Agent modes](/docs/agent/chat-and-agent-modes).',
          ),
        },
        {
          slug: 'installation',
          title: 'Installation and updates',
          description: 'Install the standalone app or use the shared Agent surface in Hub.',
          body: md(
            '# Installation and updates',
            '',
            'Download the standalone desktop installer from the [XENO Agent product page](/product/agent). The public release provides Windows and Linux artifacts. The current experimental build may present the operating-system warning described on the download page because production signing is a separate release tier.',
            '',
            '## Standalone desktop',
            '',
            'Install and launch XENO Agent normally. Mutable workspace and conversation records live under `~/.xeno/agent`; provider and session stores under `~/.xeno/` are shared with compatible XENO Agent surfaces. Closing a conversation tab does not delete its durable session.',
            '',
            '## XENO Hub',
            '',
            'Hub includes a recovery-floor Agent surface. Hub 0.11.18 can verify and load a strictly newer signed `agent@1` runtime package, allowing compatible renderer/interface releases to arrive without replacing the whole Hub application. Changes that require new privileged preload methods, Electron-main behavior, or a breaking Host protocol still require a Hub release.',
            '',
            '## Updating',
            '',
            'The standalone release and Hub-managed runtime use XENO update feeds. Finish or hand off consequential work before restarting. Session state survives restart, but an active external process is marked according to what can actually be recovered rather than displayed as still running.',
          ),
        },
        {
          slug: 'quickstart',
          title: 'Quickstart',
          description: 'Start a Chat, open a project Agent, and understand the first permission boundary.',
          body: md(
            '# Quickstart',
            '',
            '## Start a Chat',
            '',
            '1. Choose **New session** and select **Chat**.',
            '2. Pick a provider and model from the host-populated selector.',
            '3. Send a question. No project folder is requested.',
            '',
            'Chat receives a private Host-managed working directory so provider processes have a valid current directory, but that directory is not authority over one of your projects.',
            '',
            '## Start an Agent',
            '',
            '1. Choose **New session** and select **Agent**.',
            '2. Select the exact local project folder.',
            '3. Review the permission profile and allowed directories.',
            '4. Ask for a concrete task, then inspect tool calls, diffs, terminal output, and verification evidence.',
            '',
            'Agent mode refuses to start project execution without an explicit folder. This is the security boundary: application access to the filesystem is not treated as user consent for a session.',
            '',
            'You can also open the same graphical surface from the terminal with `xeno chat --interface` or `xeno agent --interface`. See [CLI and interface handoff](/docs/agent/cli-interface-handoff).',
          ),
        },
      ],
    },
    {
      title: 'Modes and workspaces',
      pages: [
        {
          slug: 'chat-and-agent-modes',
          title: 'Chat and Agent modes',
          description: 'The canonical session modes, workspace behavior, and capability boundary.',
          body: md(
            '# Chat and Agent modes',
            '',
            'Chat and Agent are runtime session modes shared by the CLI and graphical interface. They are not two unrelated products.',
            '',
            '| | Chat | Agent |',
            '|---|---|---|',
            '| Project selection | Not required | Required |',
            '| Working directory | Private Host-managed workspace | Exact user-selected project root |',
            '| Project file/command authority | Disabled | Capability and policy controlled |',
            '| Conversation, providers, attachments | Available | Available |',
            '| Resume behavior | Restores Chat authority | Restores Agent plus its workspace grant |',
            '',
            'A Chat provider still needs an operating-system current directory, so the Host creates one below the XENO data root. That implementation detail does not turn Chat into project-aware Agent mode. It prevents the old false choice between “no folder” and “implicit filesystem authority.”',
            '',
            'Mode is persisted with the session. Saved UI state or a current shell directory cannot silently promote Chat to Agent. A lane that cannot enforce a tool-disabled Chat turn fails closed instead of merely hiding buttons.',
            '',
            'Changing authority is deliberate. Choose Agent and grant a folder; do not rely on a model request such as “switch modes” to widen access.',
          ),
        },
        {
          slug: 'workspaces-and-files',
          title: 'Workspaces, files, and terminal',
          description: 'How project roots constrain file, editor, and terminal operations.',
          body: md(
            '# Workspaces, files, and terminal',
            '',
            'In Agent mode, the selected folder becomes the session workspace grant. The file tree, editor, terminal, repository context, and project-aware tools all resolve from that Host-owned grant.',
            '',
            'Path validation happens at the Host boundary, not only in the renderer. A model or UI payload cannot mint a wider directory. If another root is needed, add it through an explicit workspace/permission action and review the resulting authority.',
            '',
            'Chat mode uses a separate managed workspace. Files you explicitly attach can enter the conversation through the attachment contract, but Chat does not inherit the folder that happens to be open elsewhere.',
            '',
            'Terminal tabs and provider-native TUI sessions are distinct. A project terminal is an interactive shell in the selected workspace. An attached provider TUI is a view of that provider session; closing the view detaches it and does not implicitly kill the underlying provider process.',
          ),
        },
        {
          slug: 'permissions-and-containment',
          title: 'Permissions and containment',
          description: 'How the interface presents authority, approvals, and containment truthfully.',
          body: md(
            '# Permissions and containment',
            '',
            'The active permission profile controls whether tools can read, edit, execute, or require approval. Workspace roots bound file and command operations. Provider selection never grants more authority than the Host contract permits.',
            '',
            'Containment is reported independently from permission UX. “Allowed” means policy permits an operation; it does not prove an operating-system sandbox exists. A run can report `none`, `sandboxed`, or `unknown` containment, and unsupported containment must not be presented as active.',
            '',
            'Use full-access modes only for projects and providers you trust. Review consequential tool calls and evidence. The renderer never receives raw provider secrets or unrestricted host authority; privileged work remains behind validated Host/preload methods.',
          ),
        },
      ],
    },
    {
      title: 'Sessions and coordination',
      pages: [
        {
          slug: 'sessions-and-resume',
          title: 'Sessions, tabs, and resume',
          description: 'Durable conversation identity, cross-surface resume, and crash recovery.',
          body: md(
            '# Sessions, tabs, and resume',
            '',
            'A conversation has a durable session identity independent of the window or frontend viewing it. Mode, workspace grant, provider binding, messages, runtime events, coordination state, and nested-agent relationships are restored from Host-owned state.',
            '',
            'Conversation tabs are presentation state. `Ctrl+T` opens a session tab, `Ctrl+W` closes the visible tab without deleting its conversation, `Ctrl+Tab` and `Ctrl+Shift+Tab` move between tabs, and `Ctrl+1` through `Ctrl+9` select by position.',
            '',
            'After restart, completed persisted turns remain recoverable. An interrupted external process is not falsely shown as live. Recovery may restore the conversation and mark unfinished work interrupted so you can inspect or retry it safely.',
            '',
            'When resuming an Agent session, the original mode and exact workspace are restored. If the folder is unavailable or permission changed, the interface surfaces the failure and asks for a valid authority decision rather than silently moving the session elsewhere.',
          ),
        },
        {
          slug: 'goal-loop-handoff',
          title: 'Goal, Loop, and Handoff',
          description: 'Durable objectives, unbounded continuation, verification, and single-owner transfer.',
          body: md(
            '# Goal, Loop, and Handoff',
            '',
            'The development-lifecycle panel is a projection of the Agent SDK coordination store. The renderer does not own a competing state model.',
            '',
            '- A **Goal** records the objective, success criteria, milestones, tasks, steering, progress, and verification evidence.',
            '- A **Loop** records repeated work. Goal-continuation and agentic-development loops are unbounded unless you deliberately set a limit; a failed iteration is evidence for the next repair pass, not automatic completion.',
            '- A **Handoff** transfers the single live execution lease. Claiming the transfer advances a fencing epoch, preventing the previous owner from continuing side effects.',
            '',
            'You can create or steer goals, start/pause/resume/stop loops, inspect iteration history, and prepare or claim a handoff. Goal completion requires verified success-criterion evidence; an assistant saying “done” is not sufficient.',
            '',
            'The panel shows the current owner, epoch, objective, verification counts, active milestone/task, delegated agent, outstanding work, loop state, and handoff lineage. Navigating to another agent does not transfer execution authority.',
          ),
        },
        {
          slug: 'nested-agents',
          title: 'Nested agents',
          description: 'Delegate structured work, inspect child conversations, and navigate the agent tree.',
          body: md(
            '# Nested agents',
            '',
            'Delegation creates a real child execution context with its own prompt, messages, tool calls, results, status, and possible descendants. Parent/child identity and result routing belong to the runtime, not the currently visible component.',
            '',
            'Select a child in the agent tree to open its full conversation surface. Use **Back to parent agent** to return, or select a sibling from the tree. Execution continues regardless of which conversation you are viewing.',
            '',
            'A child receives structured scope and selected context rather than automatically copying an unlimited parent transcript. Project-aware children require a workspace grant; research or reasoning children can run without one when their tools permit it.',
            '',
            'Completed child results return to the correct parent task as structured runtime records. After restart, the hierarchy and completed conversations remain available; work that lost its process is marked interrupted rather than left as a phantom running agent.',
          ),
        },
      ],
    },
    {
      title: 'Interface and integrations',
      pages: [
        {
          slug: 'ade-workbench',
          title: 'Agent interface and ADE workbench',
          description: 'How conversation, files, terminal, review, diagnostics, and coordination form one development harness.',
          body: md(
            '# Agent interface and ADE workbench',
            '',
            'ADE is the software-development harness inside XENO Agent. It combines the conversation timeline with workspace files, Monaco editing, terminals, repository/review state, checkpoints, diagnostics, runtime events, permissions, and coordination.',
            '',
            'Tool invocations render as typed compact records from their first classified event; raw argument payloads are not intended to flash as assistant prose. Expand a tool explicitly when you need arguments or output. Large histories use incremental projections and collapsed records so changing the viewed agent does not stop execution.',
            '',
            'Capabilities are dynamic. The selected Host/provider lane reports what it can enforce, and unsupported work remains unavailable or fails closed. XENO Agent does not infer engineering capability from a model name.',
            '',
            'The standalone app, Hub embed, and other consumers mount the same shared UI. Suite chrome and native integration can differ, but session, tool, coordination, and nested-agent meaning does not.',
          ),
        },
        {
          slug: 'providers-and-models',
          title: 'Providers and models',
          description: 'Choose ACP, SDK-native, or cloud execution from live descriptors.',
          body: md(
            '# Providers and models',
            '',
            'The Host discovers execution lanes and publishes structured descriptors containing availability, models, reasoning options, and capabilities. The interface renders those descriptors rather than hardcoding provider families.',
            '',
            '- **ACP** connects approved local or service agents through XENO ACP.',
            '- **SDK-native** runs the canonical XENO Agent SDK loop through the Electron Host bridge.',
            '- **XENO Cloud** uses hosted runs through the portable cloud client.',
            '',
            'The provider selector is populated from the live Host catalog. Choosing ACP exposes only providers that the installed ACP runtime discovers, and the model selector comes from that provider\'s bounded model-discovery result. Fixture providers are reserved for tests and are not presented as user choices in a production Host.',
            '',
            'Unavailable, degraded, blocked, and approval-required states remain visible. Provider discovery and native-terminal launch are asynchronous Host operations, so changing a selector cannot block the renderer thread. An engineering turn cannot silently fall back to a text-only lane that cannot enforce its declared tools or permissions.',
            '',
            '## XENO TUI and provider-native TUI',
            '',
            '**XENO TUI** opens the canonical XENO Agent CLI attached to the current conversation and workspace. **Provider native TUI** opens the selected provider\'s own installed terminal application—such as Codex or Claude Code—attached to that provider continuation. They are different views, not skins of one another.',
            '',
            'When a native provider session is attached, user messages entered in that terminal are appended to the owning GUI conversation, and GUI turns sent through the ACP lane continue the same provider session. Detach closes the view without ending the provider session; Stop is the explicit termination action. Structured provider-only reasoning or tool presentation can remain richer in the native TUI than in the normalized GUI event stream.',
            '',
            'The Host does not paste the XENO application system prompt into a third-party CLI conversation. The provider keeps its own system instructions; XENO supplies only the scoped user turn, selected model, workspace, and execution/permission policy required by the lane.',
          ),
        },
        {
          slug: 'cli-interface-handoff',
          title: 'CLI and interface handoff',
          description: 'Open the exact CLI session in the graphical surface without copying it.',
          body: md(
            '# CLI and interface handoff',
            '',
            'The CLI and graphical interface are clients of the same session model. Open the current or resumed session in the desktop surface with:',
            '',
            '```powershell',
            'xeno chat --interface',
            'xeno agent --interface',
            'xeno agent --resume <session-id> --interface',
            '```',
            '',
            '`xeno chat --interface` opens XENO Chat with Chat-only authority. `xeno agent --interface` preserves the exact granted local workspace even if the desktop already has Chat history. The launch uses a nonce-bound acknowledgement so an older app that merely starts but cannot resume the session is reported as incompatible rather than success.',
            '',
            'A live execution handoff is stronger than opening a view: it flushes the transcript, transfers the lease, advances the fencing epoch, and prevents the source from appending after the target claims ownership.',
          ),
        },
        {
          slug: 'web-browser-computer-use',
          title: 'Web, browser, and computer use',
          description: 'The separation between retrieval, controlled browser automation, and device action.',
          body: md(
            '# Web, browser, and computer use',
            '',
            'XENO separates public-web retrieval from interactive control:',
            '',
            '- Search and structured page retrieval belong to the Web Context/search tool path.',
            '- Native browser navigation and interaction use the governed browser automation contract and an available XENO Browser adapter.',
            '- Acting on an existing desktop application or browser window uses a computer-use/device adapter such as XENO Use when that adapter is installed and certified.',
            '',
            'The Agent SDK contract enforces exact capability leases, target preflight, read-versus-act domain policy, bounded evidence, idempotency, cancellation, and human stop. Adapter availability and native containment certification are separate facts. If the Host does not advertise a certified adapter for the requested operation, the interface must not imply that browser or device control is active.',
          ),
        },
        {
          slug: 'research-and-web-evidence',
          title: 'Research and web evidence',
          description: 'Run bounded public-web research, follow progress, stop work, and understand citation persistence.',
          body: md(
            '# Research and web evidence',
            '',
            'In hosted XENO Chat, use **Research** in a saved conversation when an answer needs current public-web sources. XENO Chat submits the public query to XENO Web Context, shows canonical queued/searching/fetching progress, and attaches server-issued evidence to the assistant turn. **Quick** uses a smaller page and cost budget; **Deep** permits a larger bounded investigation.',
            '',
            'Research is separate from browser control. It retrieves public sources under explicit page, byte, duration, concurrency, redirect, and provider-cost limits. It does not receive workspace files, cookies, account secrets, private URLs, or the rest of an authenticated browser session.',
            '',
            'Press **Stop** while Research is running to request cancellation of the durable Web Context job. The UI keeps observing until cancellation is confirmed or reports that confirmation was unavailable; closing the HTTP stream alone is not treated as a successful stop.',
            '',
            '## Citations and reload',
            '',
            'A completed durable result stores a single-use server receipt with the assistant message. On reload, citations are reconstructed from that persisted receipt rather than trusted from browser-supplied message JSON. The server rejects forged, expired, reused, cross-user, or cross-conversation receipts.',
            '',
            'The configured search provider must explicitly permit API-result persistence before a durable Research job can start. The current hosted Brave approval is transient-only, so XENO refuses durable Research with `web_context_storage_not_approved` instead of spending a request and silently storing prohibited result data. Ordinary Chat remains available. Increasing provider throughput does not itself grant storage permission.',
            '',
            'Related: [Storage and recovery](/docs/agent/storage-and-recovery) · [Troubleshooting](/docs/agent/troubleshooting).',
          ),
        },
        {
          slug: 'agent-runtime-updates',
          title: 'Independent interface updates',
          description: 'When an Agent interface update can ship without a full Hub installer.',
          body: md(
            '# Independent interface updates',
            '',
            'Compatible Agent renderer releases can ship as signed packages declaring the `agent@1` contract. Hub verifies the package and handshake, then uses the newer surface instead of its bundled recovery floor.',
            '',
            'This is intentionally narrower than arbitrary application replacement. The runtime package receives only the existing request, event, and shell contract. It cannot introduce privileged Electron-main authority. Verification failure, an unsupported contract, handshake failure, or a render exception falls back to the bundled surface.',
            '',
            'A Hub installer release is still required for a new privileged preload method, Electron/native dependency, trust-key change, or breaking Host protocol revision.',
          ),
        },
      ],
    },
    {
      title: 'Reference and help',
      pages: [
        {
          slug: 'storage-and-recovery',
          title: 'Storage and recovery',
          description: 'The local data layout and what survives restart.',
          body: md(
            '# Storage and recovery',
            '',
            'XENO Agent stores local authority and state below `~/.xeno/`:',
            '',
            '| Path | Purpose |',
            '|---|---|',
            '| `agent-host-v1/` | Per-user Host authority, lease, RPC, and workspace-policy root |',
            '| `agent/state.sqlite` | Mutable workspace and conversation records |',
            '| `agent/backups/` | Content-hashed pre-migration backups |',
            '| `agent/reports/` | Migration and repair reports |',
            '| `runtime-events/` | Runtime event history |',
            '| `acp-chat-workspaces/` | Managed Chat-mode ACP workspaces |',
            '',
            'Migrations stage a temporary target, verify equivalence, and activate atomically. Tests and certification use isolated profiles rather than the operator profile. Back up the XENO data root before manual repair, and do not edit active SQLite or lease files while an Agent process is running.',
          ),
        },
        {
          slug: 'keyboard-shortcuts',
          title: 'Keyboard shortcuts',
          description: 'Navigate durable session tabs from the keyboard.',
          body: md(
            '# Keyboard shortcuts',
            '',
            '| Shortcut | Action |',
            '|---|---|',
            '| `Ctrl+T` | Open a new session tab |',
            '| `Ctrl+W` | Close the visible tab without deleting its conversation |',
            '| `Ctrl+Tab` | Select the next tab |',
            '| `Ctrl+Shift+Tab` | Select the previous tab |',
            '| `Ctrl+1` … `Ctrl+9` | Select a tab by position |',
            '| `Ctrl+K` | Open documentation search on the website |',
            '',
            'Provider-native terminal applications can define additional shortcuts inside their attached terminal. Those do not replace the Agent application-level session navigation contract.',
          ),
        },
        {
          slug: 'troubleshooting',
          title: 'Troubleshooting',
          description: 'Recover from workspace, provider, resume, update, tool-rendering, and handoff problems.',
          body: md(
            '# Troubleshooting',
            '',
            '## Agent asks for a folder',
            '',
            'You selected Agent mode. Choose the exact project root. If you only want conversation, start or resume a Chat session instead.',
            '',
            '## A provider is visible but will not run',
            '',
            'Inspect its status. Approval, policy, authentication, implementation, and capability negotiation must all agree. The Host fails closed when they do not.',
            '',
            '## Provider selection freezes or shows a fixture',
            '',
            'Update the Host and Agent runtime together. Production selectors must use the asynchronous live provider catalog and must filter fixture-only definitions. Capture the provider-catalog diagnostic if changing lanes blocks the window or a fixture remains selectable.',
            '',
            '## Native TUI asks to trust an already granted workspace',
            '',
            'The Host maps the explicit Agent workspace grant into the provider\'s supported non-interactive trust or permission flags. If the provider still prompts, do not create a second hidden grant; capture the provider version and launcher diagnostic because the installed CLI may have changed its trust contract.',
            '',
            '## Native TUI messages do not appear in the GUI',
            '',
            'Confirm that the terminal says it is attached to the same conversation and provider session. Detach and reattach from that conversation. The Host follows the provider\'s persisted user-message transcript; it does not scrape terminal pixels or copy a different session.',
            '',
            '## Research says durable citations are unavailable',
            '',
            'The configured search-provider approval does not permit API-result persistence. Retry in ordinary Chat if you do not need public-web evidence. An operator must record a storage-granting provider plan before durable Research can be enabled; increasing request capacity alone does not clear this gate.',
            '',
            '## Research was stopped but cancellation is unconfirmed',
            '',
            'Wait for the terminal status before starting the same investigation again. XENO sends one durable cancellation request and observes its confirmation; it does not issue duplicate cancels or pretend that closing the browser stream stopped the remote job.',
            '',
            '## Resume opens the wrong authority',
            '',
            'Confirm the session ID and whether it was created as Chat or Agent. Resume restores the persisted mode; a shell current directory does not override it. For a CLI handoff, use the exact command printed by the CLI and require the desktop acknowledgement.',
            '',
            '## A child still says running after restart',
            '',
            'Refresh durable state. A process that no longer exists should become interrupted, not remain live. Preserve support data and report the session ID if it does not reconcile.',
            '',
            '## A tool card flashes or freezes the timeline',
            '',
            'Update to the current runtime surface. Tool events should classify before rendering and remain collapsed until expanded. Capture a support bundle with the affected event type and payload size; do not paste credentials or raw secrets.',
            '',
            '## A handoff source can still execute',
            '',
            'Stop consequential work immediately. A successful target claim must advance the fencing epoch and make source renewal fail. Record both owner IDs, the handoff ID, and the durable coordination state for diagnosis.',
            '',
            'See [release notes](/product/agent/releases) for fixed versions and update guidance.',
          ),
        },
      ],
    },
  ],
};

export default agent;
