import type { ProductDocs } from './_types';

/* XENO Apps documentation — authored from ../xeno-apps @ feat/phase-a SOURCE,
 * verified 2026-08-08. Do NOT re-source from that repo’s README/SPEC/CHANGELOG:
 * all three are stale (the CHANGELOG still says "no application code yet" and
 * the SPEC describes exec wires, a xeno-workflow engine, sandboxed JS, AI nodes
 * and web export — none of which exist). The honesty contract that governs this
 * product’s public copy lives in src/content/products/apps.ts; read it before
 * editing a page here.
 *
 * Markdown bodies are assembled with body(...) so that every line is an ordinary
 * quoted string — code fences can then contain backticks with no escaping, which
 * is the failure mode PRODUCT-LANDING-SPEC §7.5 warns about. */

const body = (...lines: string[]): string => lines.join('\n');

const apps: ProductDocs = {
  slug: 'apps',
  productName: 'XENO Apps',
  tagline: 'Compose an internal tool out of first-party panels, wire it to real data, and save it as one .xapp file.',
  seo: {
    title: 'XENO Apps documentation',
    description: 'Build a desktop app from 21 first-party panels: place them on a workbench, wire them in FRONT or on the BACK node canvas, connect HTTP, GraphQL, CSV or JSON data behind per-origin approval, and save a single .xapp file.',
  },
  sections: [
    {
      title: 'Getting Started',
      pages: [
        {
          slug: 'introduction',
          title: 'Introduction',
          description: 'What XENO Apps is, the one idea it is built on, and an honest list of what does and does not work in v0.1.0.',
          body: body(
            '## What XENO Apps is',
            '',
            'XENO Apps is a desktop builder for the kind of tool you would otherwise ask an engineer for — an internal dashboard, a view over an API, a grid on top of a CSV. You compose it out of **panels**: self-contained pieces of interface that declare what data they read, what data they emit, and what commands they accept.',
            '',
            'The panels are not props. They are the same first-party components the rest of the XENO stack is built from, which is why a first release of a builder ships with a table, a chart, a tree and an inspector that are already finished.',
            '',
            'There are two ways to look at the app you are building, and this is the one idea worth understanding before anything else:',
            '',
            '- **FRONT** is the app as its user sees it — real panels, docked in a workbench, showing real data.',
            '- **BACK** is the same app drawn as a node canvas, where you can drop a transform between two panels.',
            '',
            'These are **two projections of one graph**, not two documents kept in sync. BACK is drawn over the top while FRONT stays mounted underneath it, so there is no synchronisation step that can go wrong and no way for the two views to disagree.',
            '',
            '## What works in v0.1.0',
            '',
            '- The workbench, the panel library, and all 21 first-party panels.',
            '- Real data: HTTP, GraphQL, CSV files, JSON files, and pasted-in rows.',
            '- Per-origin network approval, enforced before a connection is opened.',
            '- Credential storage in the operating system’s keystore.',
            '- Wiring in both views, with type-checked connections.',
            '- Multiple instances of a panel, each with its own configuration.',
            '- Authoring undo and redo.',
            '- Run-on-open triggers, five starter templates, and `.xapp` save/open.',
            '- A Panel Studio for writing your own panel, run in an isolated frame.',
            '',
            '## What does not work yet',
            '',
            'This list is deliberately explicit. Nothing below is implemented, and some of it appears in older design documents in the product repository — treat those as intent, not description.',
            '',
            '- **No AI.** Despite the product category, nothing in this build calls a model. The inference runtime, media library, workflow engine and agent SDK are not wired in.',
            '- **No publishing or sharing.** You save a `.xapp` file. There is no share link, no web export, no marketplace, and no way to hand a running app to someone who does not have XENO Apps installed.',
            '- **No automatic updates.** There is no updater in the application; a new version means downloading it again.',
            '- **No SQL or database sources.**',
            '- **No execution wires.** Connections carry data only, so there is no retry, no checkpointing and no execution-order guarantee. Ordering at open time is the trigger list, described in [Run triggers](/docs/apps/run-triggers).',
            '- **Windows only.** macOS and Linux build targets are configured but not built.',
            '',
            '## Where to go next',
            '',
            '- Install it and build something: [Installation](/docs/apps/installation), then [Your first app](/docs/apps/quickstart).',
            '- Understand the model: [Panels](/docs/apps/panels) and [FRONT and BACK](/docs/apps/front-and-back).',
            '- Connect real data: [Data sources](/docs/apps/data-sources) and [Consent and credentials](/docs/apps/consent-and-credentials).',
          ),
        },
        {
          slug: 'installation',
          title: 'Installation',
          description: 'Platform support, what Windows will say about an unsigned build, and where XENO Apps keeps your files.',
          body: body(
            '## Platform support',
            '',
            'XENO Apps v0.1.0 ships as a **Windows x64 installer**. macOS and Linux targets exist in the build configuration, but no build has been produced for either and the end-to-end test evidence is Windows only.',
            '',
            '## The installer is not code-signed',
            '',
            'v0.1.0 is an experimental first release and is **not code-signed**. Windows SmartScreen will show *“Windows protected your PC”* when you run it. To continue, choose **More info → Run anyway**. If that is not acceptable on your machine, wait for a signed build.',
            '',
            '## It does not update itself',
            '',
            'There is no updater in this build. When a new version is published you download it from the product page again. Nothing in the application checks for updates, and nothing phones home.',
            '',
            '## File association',
            '',
            'The installer registers `.xapp` as a XENO Apps document, so double-clicking a saved app opens it in the builder.',
            '',
            '## Where your data lives',
            '',
            '| What | Where |',
            '|---|---|',
            '| Your apps | Wherever you save them — a `.xapp` is an ordinary file you choose the location of |',
            '| Approved origins | The app’s user-data directory, as a consent store |',
            '| Credentials | The operating system keystore (DPAPI on Windows) — never in the app’s own files |',
            '',
            'Nothing is uploaded anywhere by the application itself. The only network traffic is the requests your own data sources make, to origins you have explicitly approved.',
            '',
            '## Next',
            '',
            'Build something: [Your first app](/docs/apps/quickstart).',
          ),
        },
        {
          slug: 'quickstart',
          title: 'Your first app',
          description: 'Open a starter, add a data source, approve the origin, place a table, wire a chart, save it and reopen it.',
          body: body(
            'This walkthrough builds a small dashboard end to end. It covers the whole loop the builder is designed around: **open → add a source → approve → place → wire → save → reopen**. It takes a few minutes and touches every concept in the rest of these docs.',
            '',
            '## 1. Open a starter',
            '',
            'On launch, choose **File → New from Template…**. Five starters ship with the app:',
            '',
            '| Template | What it gives you |',
            '|---|---|',
            '| Support desk dashboard | Metrics tiles, a table and a chart already wired together |',
            '| Records and detail | A list beside a detail inspector |',
            '| Service monitor | Status-oriented panels |',
            '| Review workspace | A diff-and-comment layout |',
            '| Blank app | An empty workbench |',
            '',
            'Pick **Blank app** to follow along from nothing, or **Support desk dashboard** to see a finished composition first. The starters are not checked-in files — they are built through the same API you drive by hand, so anything a template does, you can do.',
            '',
            '## 2. Add a data source',
            '',
            'Place the **Connectors** panel from the library on the left, then add a source. Five kinds are available:',
            '',
            '- **Paste data** — rows you type or paste in, useful for sketching a layout.',
            '- **HTTP endpoint** — a URL returning JSON.',
            '- **GraphQL** — an endpoint plus a query document.',
            '- **CSV file** / **JSON file** — picked from disk.',
            '',
            'Choose **HTTP endpoint** and give it a URL. Requests are made from the application’s main process rather than from a browser context, so cross-origin restrictions are not something you have to work around.',
            '',
            '## 3. Approve the origin',
            '',
            'The first time a source tries to reach a host, XENO Apps asks you to approve it. Until you do, **the host is unreachable** — the check happens before a connection is opened, not by discarding the response afterwards.',
            '',
            'The consent sheet shows the origin verbatim so you can read exactly what is being requested. Approval is per origin — scheme, host and port. You can review and revoke every grant later under **File → Permissions…**.',
            '',
            'If your endpoint needs a key, store it now: it goes into the operating system keystore, and your app holds only a reference to it. See [Consent and credentials](/docs/apps/consent-and-credentials).',
            '',
            '## 4. Place a table',
            '',
            'Drag the **Table** panel from the library onto a slot in the workbench. Select it and open its configuration to point it at the source you just created. You should now see real rows.',
            '',
            'Need a second table? Drag it on again. Each instance keeps its own configuration and its own state — the first is `xeno.core.table`, the next is `xeno.core.table#2`.',
            '',
            '## 5. Wire a chart',
            '',
            'Add the **Chart** panel, then connect the table to it. There are two ways, and they edit the same graph:',
            '',
            '- **In FRONT**, use the Wiring panel to pick a source port and a destination port.',
            '- **In BACK**, switch views from the menu bar and drag from one node’s pin to another. You can drag in either direction, and the wire snaps to the nearest **type-compatible** port — the canvas will not offer you a connection the graph would refuse.',
            '',
            'Wire the table’s selection output into the chart’s input, and the chart will follow whatever row you select.',
            '',
            '## 6. Make it show data on open',
            '',
            'Save and reopen now and you would get your layout back but an empty table, because a freshly opened app has nothing pushing data yet. Add a **run trigger**: a command fired automatically after the app opens, such as telling the connector to fetch. See [Run triggers](/docs/apps/run-triggers).',
            '',
            '## 7. Save and reopen',
            '',
            'Choose **File → Save**. XENO Apps writes a single `.xapp` file: indented JSON describing your panels, their configuration and layout, your wires, any logic nodes, and your triggers.',
            '',
            'Close the app and open the file again. The layout, the configuration, the wires and the triggers all come back, and the trigger repopulates the data. Your credentials are *not* in the file — they stayed in the keystore.',
            '',
            'Made a mistake along the way? **Ctrl+Z** walks back through your authoring: wires, logic nodes, placement, instances and configuration.',
            '',
            '## Next',
            '',
            '- [Panels](/docs/apps/panels) — what you are composing with.',
            '- [FRONT and BACK](/docs/apps/front-and-back) — why the two views cannot disagree.',
            '- [The .xapp format](/docs/apps/xapp-format) — what you just saved.',
          ),
        },
      ],
    },
    {
      title: 'Core Concepts',
      pages: [
        {
          slug: 'panels',
          title: 'Panels',
          description: 'The unit you build with: a declared contract of ports, commands and configuration — and the 21 that ship.',
          body: body(
            '## What a panel is',
            '',
            'A panel is a self-contained piece of interface with a **declared contract**. It states, in a manifest:',
            '',
            '- the **input ports** it reads and the **output ports** it emits, each with a type;',
            '- the **commands** it accepts;',
            '- the **configuration fields** it exposes.',
            '',
            'Because that contract is declared rather than assumed, the builder can connect two panels that know nothing about each other. It is also why your configuration UI exists without anyone designing it per panel: XENO Apps projects each panel’s declared fields into a standard inspector.',
            '',
            'Panels come from the shared XENO panel library, not from this application — the same components are used by the creative apps in the stack. XENO Apps composes them; it does not own them.',
            '',
            '## The 21 panels',
            '',
            '| Panel | Id | What it is for |',
            '|---|---|---|',
            '| Table | `xeno.core.table` | Rows and columns, with selection as an output |',
            '| Chart | `xeno.core.chart` | Plot a series |',
            '| Metrics | `xeno.core.metrics` | KPI tiles |',
            '| Tree | `xeno.core.tree` | Hierarchical data |',
            '| Fields | `xeno.core.fields` | A form over a record |',
            '| Calendar | `xeno.core.calendar` | Date-oriented data |',
            '| Connectors | `xeno.core.connectors` | Define and manage data sources |',
            '| Inspector | `xeno.core.inspector` | Schema-driven properties for a selection |',
            '| Layers | `xeno.core.layers` | An ordered, nestable list |',
            '| History | `xeno.core.history` | An undo stack you can jump around in |',
            '| Transport | `xeno.core.transport` | Play, pause and scrub a timeline |',
            '| Viewport | `xeno.core.viewport` | A device-pixel-correct render surface |',
            '| Console | `xeno.core.console` | Log output, with secret redaction on ingest |',
            '| Runs | `xeno.core.runs` | A list of executions |',
            '| Terminal | `xeno.core.terminal` | A terminal surface |',
            '| Diff | `xeno.core.diff` | Compare two versions and accept hunks |',
            '| Find | `xeno.core.find` | Search and filter |',
            '| Comments | `xeno.core.comments` | Threaded annotations |',
            '| Consent | `xeno.core.consent` | Approve or refuse a pending request |',
            '| Account | `xeno.core.account` | Identity and plan surface |',
            '| Color | `xeno.core.color` | Pick and commit a color |',
            '',
            '> The Terminal panel in v0.1.0 is backed by a **scripted emulator**, not a real shell. It demonstrates the panel and its contract; it does not run commands on your machine.',
            '',
            'The panel library in the app also lists a few clearly-labelled demo tiles alongside these, used for examples.',
            '',
            '## Multiple instances',
            '',
            'Any panel can be placed more than once. The first instance keeps the plain manifest id; later ones take an ordinal suffix:',
            '',
            '```',
            'xeno.core.table      the first Table',
            'xeno.core.table#2    the second Table',
            '```',
            '',
            'Each instance has its own configuration, its own state and its own identity in the graph, so a wire addresses one specific table. Removing an instance frees its ordinal for reuse.',
            '',
            '## Configuration',
            '',
            'Selecting a panel shows its declared configuration fields in the inspector. Two current limitations are worth knowing:',
            '',
            '- Code-valued fields render as a plain text area, without highlighting or validation.',
            '- Several panels read their configuration once when they start, so an edit to those fields takes effect when the panel is remounted rather than instantly.',
            '',
            '## Next',
            '',
            '[FRONT and BACK](/docs/apps/front-and-back) — how these panels become a graph.',
          ),
        },
        {
          slug: 'front-and-back',
          title: 'FRONT and BACK',
          description: 'One graph, two projections — how the working app and the node canvas stay incapable of disagreeing.',
          body: body(
            '## Two views, one object',
            '',
            'Switch between **FRONT** and **BACK** from the menu bar.',
            '',
            '- **FRONT** renders your app the way its user will see it: panels docked into slots, live, showing real data.',
            '- **BACK** renders the same app as a node canvas: every placed panel is a node, drawn with the ports its manifest declares.',
            '',
            'The important property is that there is exactly **one graph**. The same wire list, the same logic nodes and the same panel positions back both views. Opening BACK does not build a second model of your app — it draws over the top while FRONT stays mounted underneath. There is no synchronisation step, and therefore nothing for it to get wrong.',
            '',
            'This is also why a panel needs no adapter to appear as a node. The canvas reads the ports straight off the panel’s manifest.',
            '',
            '## Wiring',
            '',
            'Connections carry **data**. A wire takes an output port on one node to a compatible input port on another.',
            '',
            'In **BACK**, drag from a pin. You can start at either end, and the drag snaps to the nearest **type-compatible** port — using the same compatibility rule that validates the wire, so the canvas can never snap you to a connection the graph would then reject.',
            '',
            'In **FRONT**, the Wiring panel offers the same operation as a pair of selections rather than a gesture.',
            '',
            '> There are no execution wires in v0.1.0. Connections carry data only. That means there is no execution order to configure, and no retry, checkpointing or determinism guarantee — if you have read otherwise in an older design document, it describes an intended future, not this build.',
            '',
            '## Logic nodes',
            '',
            'Some steps do not belong to any panel — reshaping a payload, filtering a list, branching on a value. Those are **logic nodes**: they live only in BACK, have no FRONT surface, and are addressed by wires exactly like panels, because it is one graph.',
            '',
            'Eight types ship:',
            '',
            '| Node | What it does |',
            '|---|---|',
            '| `expression` | Evaluate an expression over the input |',
            '| `map` | Transform each item |',
            '| `filter` | Keep items matching a condition |',
            '| `text-formatter` | Build a string from input values |',
            '| `json-transform` | Reshape a JSON payload |',
            '| `if-else` | Branch on a condition |',
            '| `switch` | Branch on a value across several cases |',
            '| `code` | A restricted expression body over the input |',
            '',
            '> The `code` node is **not** a JavaScript sandbox. It evaluates a restricted expression grammar. A general scripting substrate is future work.',
            '',
            '## Next',
            '',
            '[Data sources](/docs/apps/data-sources) — getting real values into the graph.',
          ),
        },
        {
          slug: 'run-triggers',
          title: 'Run triggers',
          description: 'Why a reopened app starts empty, and how to make it fetch its data on open.',
          body: body(
            '## The problem they solve',
            '',
            'Data wires are **push-primary**: a value moves along a wire when something emits it. That is fine while you are working, because you have just clicked something. It is not fine on a cold open — you reopen a saved app, the graph is restored perfectly, and every panel is empty because nothing has emitted yet.',
            '',
            '**Run triggers** are the fix. A trigger is a command fired automatically once the app has opened.',
            '',
            '## Defining one',
            '',
            'A trigger names a node, a command on that node, and optional parameters:',
            '',
            '```json',
            '{ "node": "xeno.core.connectors", "command": "refresh" }',
            '```',
            '',
            'Triggers are stored in the `onOpen` list of your `.xapp` and run in order. You can also fire them by hand with the **Run** button while building.',
            '',
            '## They cannot reach undeclared commands',
            '',
            'Every trigger is validated against the target panel’s **declared** commands. A hand-edited or malicious `.xapp` cannot use a trigger to invoke something a panel never advertised — the command has to exist in the manifest, or the file is rejected.',
            '',
            '## Next',
            '',
            '[The .xapp format](/docs/apps/xapp-format).',
          ),
        },
      ],
    },
    {
      title: 'Data',
      pages: [
        {
          slug: 'data-sources',
          title: 'Data sources',
          description: 'The five source kinds, how requests are actually made, and what is not supported.',
          body: body(
            '## The five kinds',
            '',
            '| Kind | You provide | Needs approval |',
            '|---|---|---|',
            '| Paste data | Rows typed or pasted in | No |',
            '| HTTP endpoint | A URL | **Yes** |',
            '| GraphQL | An endpoint URL and a query document | **Yes** |',
            '| CSV file | A file picked from disk | No |',
            '| JSON file | A file picked from disk | No |',
            '',
            'Add and manage sources from the **Connectors** panel.',
            '',
            '## How requests are made',
            '',
            'Network requests are issued from the application’s **main process**, not from the renderer. That is a deliberate choice: it means the browser’s cross-origin rules are not a constraint on which APIs you can call, so you do not have to configure anything on the server just to read from it.',
            '',
            'Requests are bounded. Only `http:` and `https:` are allowed, there is a request deadline, and there is a ceiling on response size, so a hung or enormous endpoint cannot take the app down with it.',
            '',
            '## GraphQL',
            '',
            'The GraphQL executor handles the case that catches naive clients: a GraphQL server answers **200 OK** and reports failure inside an `errors` array in the body. Partial data — errors *and* usable data in the same response — is handled rather than discarded, and authentication, authorisation and rate-limit errors are recognised as such.',
            '',
            'In v0.1.0 the source dialog collects the endpoint, the query document and the path to the rows. **Query variables and paging configuration are not exposed in the dialog yet.**',
            '',
            '## Files',
            '',
            'CSV and JSON files are read through an opaque handle rather than by holding a path in the interface. CSV parsing handles the awkward real-world cases — quoted commas, escaped quotes, and leading-zero values such as `007` staying text instead of silently becoming a number.',
            '',
            '## Not supported in v0.1.0',
            '',
            '- **SQL and database sources.** Postgres, MySQL, SQLite and DuckDB appear in the wider connector library but have no engine behind them in this application.',
            '- **Parquet files.**',
            '- Other XENO products as sources.',
            '',
            '## Next',
            '',
            '[Consent and credentials](/docs/apps/consent-and-credentials).',
          ),
        },
        {
          slug: 'consent-and-credentials',
          title: 'Consent and credentials',
          description: 'Per-origin approval enforced before a socket opens, and secrets that live in the OS keystore with no read-back.',
          body: body(
            '## Approval is per origin, and it comes first',
            '',
            'A host that you have not approved is **unreachable**. The check runs in the main process **before a connection is opened** — this is not a filter applied to a response after the fact, and there is no request to intercept because none was made.',
            '',
            'A grant covers one origin: scheme, host and port. `https://api.example.com` and `https://api.example.com:8443` are different grants.',
            '',
            'The consent sheet shows the origin **verbatim**, so what you are approving is exactly what you can read. Plain `http:` to anything other than a loopback address is flagged — local development servers and appliances are legitimate, so they are allowed, but you are told what you are agreeing to.',
            '',
            'Review and revoke grants under **File → Permissions…**. Revocation applies to the next request.',
            '',
            '> If the file storing your grants is damaged or unreadable, XENO Apps **fails closed** — a consent record it cannot read is a consent record it does not honour.',
            '',
            '## Credentials',
            '',
            'Secrets are stored in the **operating system keystore** through Electron’s `safeStorage` — DPAPI on Windows, Keychain on macOS, libsecret or KWallet on Linux.',
            '',
            'What your app holds is a **reference**, not a value:',
            '',
            '```',
            '$cred:api-token',
            '```',
            '',
            'Three properties follow from that, and they are the reason it is built this way:',
            '',
            '1. **There is no read-back channel.** The application deliberately ships no message that returns a secret to the interface. Listing credentials returns metadata only. Resolution happens in the main process, at the moment a request is built.',
            '2. **Nothing is written to your `.xapp`.** The file carries the reference; the value never leaves the keystore.',
            '3. **It refuses rather than pretends.** If the operating system keystore is unavailable, storing a credential **fails** instead of writing bytes that merely look protected.',
            '',
            '## What this means when you share a file',
            '',
            'A `.xapp` is safe to commit or send: it contains no credentials and no absolute paths. The consequence is that whoever opens it supplies their own — they will approve the origins themselves and store their own keys.',
            '',
            '## Next',
            '',
            '[The .xapp format](/docs/apps/xapp-format).',
          ),
        },
      ],
    },
    {
      title: 'Reference',
      pages: [
        {
          slug: 'xapp-format',
          title: 'The .xapp format',
          description: 'A single JSON file describing the composition — its seven keys, what a panel entry holds, and what is deliberately absent.',
          body: body(
            '## One file, plain JSON',
            '',
            'An app saves as a single `.xapp`: indented JSON, human-readable and diffable in a pull request. It is not an archive and nothing is compressed.',
            '',
            'It serialises the **composition only**. Panel implementations are referenced by manifest id and resolved from the registry when the file is opened — never embedded — which is what keeps the file small enough to read.',
            '',
            '## The seven top-level keys',
            '',
            '```json',
            '{',
            '  "format": "xapp",',
            '  "version": 1,',
            '  "app": { "name": "Support desk" },',
            '  "panels": [],',
            '  "wires": [],',
            '  "logicNodes": [],',
            '  "onOpen": []',
            '}',
            '```',
            '',
            '| Key | Contents |',
            '|---|---|',
            '| `format` | Always `"xapp"` |',
            '| `version` | Format version — currently `1` |',
            '| `app` | `{ name }` |',
            '| `panels` | Every placed panel instance |',
            '| `wires` | Data connections between nodes |',
            '| `logicNodes` | BACK-only transform and branch nodes |',
            '| `onOpen` | Triggers fired after the app opens |',
            '',
            '## A panel entry',
            '',
            '```json',
            '{',
            '  "instanceId": "xeno.core.table#2",',
            '  "manifestId": "xeno.core.table",',
            '  "version": "1.0.0",',
            '  "config": {},',
            '  "state": null,',
            '  "layout": { "position": "center", "order": 1, "visible": true },',
            '  "back": { "x": 320, "y": 140 }',
            '}',
            '```',
            '',
            '`layout` positions the panel in FRONT; `back` positions the same instance on the BACK canvas. One instance, two projections — the file reflects the same idea the views do.',
            '',
            '## What is not in the file',
            '',
            '- **No credentials.** Only `$cred:` references.',
            '- **No absolute paths.**',
            '- **No panel code.**',
            '',
            '## How it is validated',
            '',
            'The parser rejects malformed panel, wire, node and trigger entries with a specific message rather than silently dropping them, and it **refuses a file written by a newer format version** instead of half-reading it. Triggers are checked against each panel’s declared commands, so a hand-edited file cannot reach a command a panel never advertised.',
            '',
            'Saved files are also size-limited, which is a practical bound on what a single composition can carry.',
            '',
            '## Next',
            '',
            '[Panel Studio](/docs/apps/panel-studio) — writing a panel of your own.',
          ),
        },
        {
          slug: 'panel-studio',
          title: 'Panel Studio',
          description: 'Write your own panel and run it in an isolated frame — including a frank account of what that isolation does and does not give you.',
          body: body(
            '## Writing a panel',
            '',
            'When the first-party panels are not enough, open **Panels → New Panel…**. You write a panel against the same contract every first-party panel implements: declare your ports, commands and configuration fields, and reach the host only through the declared surface.',
            '',
            'Your panel is added to the catalog of **this installation**, and can then be placed and wired like any other.',
            '',
            '## How it is isolated',
            '',
            'An authored panel does not run in the application. It loads in an **opaque-origin iframe** over a custom scheme, with:',
            '',
            '- `sandbox="allow-scripts"` and **no** `allow-same-origin`;',
            '- a content policy of `default-src none`;',
            '- no network, no filesystem and no GPU.',
            '',
            'It communicates with the host only by message, over the same declared contract used everywhere else.',
            '',
            '## Capabilities',
            '',
            '| Capability | Status in v0.1.0 |',
            '|---|---|',
            '| `storage.local` | **Grantable** |',
            '| `net.fetch` | Refused at load |',
            '| `fs.read`, `fs.write` | Refused at load |',
            '| `gpu` | Refused at load |',
            '| `rt.infer`, `lib.process`, `clipboard`, `agent.invoke` | Load, but unavailable — no service is provided |',
            '',
            '## The honest limitation',
            '',
            'This is a **plain iframe, not a JavaScript isolate.** The origin boundary is real and the capability refusals are real, but there is no execution watchdog: a panel that runs an infinite loop will **hang its own frame**. Write accordingly, and treat the sandbox as a boundary against reach rather than against runaway code.',
            '',
            '## Where a panel can go',
            '',
            'Nowhere else, yet. An authored panel lives in your installation’s catalog. There is no marketplace, no packaging step and no way to publish or send one to another user.',
          ),
        },
      ],
    },
  ],
};

export default apps;
