import type { ProductDocs } from './_types';

const hub: ProductDocs = {
  "slug": "hub",
  "productName": "XENO Hub",
  "tagline": "The desktop home for the XENO ecosystem — launch every app, run the agent, manage models and credits, and keep your work local-first.",
  "version": "0.11.18",
  "updated": "2026-08-30",
  "seo": {
    "title": "XENO Hub documentation",
    "description": "Install and use XENO Hub — the Electron desktop launcher and control plane for the XENO ecosystem: apps, marketplace, the built-in AI agent, local and cloud models, credits, utility tools, and auto-updates."
  },
  "sections": [
    {
      "title": "Getting started",
      "pages": [
        {
          "slug": "introduction",
          "title": "Introduction",
          "description": "What XENO Hub is, and where it fits in the XENO ecosystem.",
          "body": "## Introduction\n\n**XENO Hub** is the desktop home for the entire XENO ecosystem. It is a single Electron application that lets you sign in once, launch and update every XENO app, talk to a built-in AI agent, install and run models locally or in the cloud, manage your credits, and use a suite of everyday creative and productivity tools — all from one window.\n\nHub is **Layer 1 (Platform & Infrastructure)** of XENO Corporation: it is both the launcher your apps run from and the control plane that ties them to your account, your credits, and the model runtimes behind them.\n\n## What it does\n\n- **App launcher** — install, launch, update, and stop XENO's creative and productivity apps (Pixel, Motion, Sound, Docs, and more) from one place.\n- **Marketplace / Store** — browse and install apps, panels, plugins, MCP servers, models, and agents, with entitlements tied to your account.\n- **Built-in AI agent** — a full agent surface with tools, permission profiles, and workspaces, powered by the XENO agent SDK.\n- **Models** — a cloud model catalog through the XENO API, plus local model install and inference through the xeno-rt runtime.\n- **Tools** — image generation, upscaling, background removal, format conversion, PBR material generation, screen capture, voice-to-text, and more.\n- **Credits & account** — view your balance and transaction history, top up, and manage your XENO account.\n- **Auto-updates** — Hub keeps itself and your installed apps current automatically.\n\n## Local-first by design\n\nHub is split across three ownership boundaries so your work survives restarts and degraded connectivity:\n\n| Surface | Owner | Role |\n|---------|-------|------|\n| `~/.xeno/` | Desktop app | Local-first storage for settings, workspaces, conversations, and caches |\n| `xenostudio.ai` | Platform backend | Sign-in, account flows, product APIs, durable account metadata |\n| `api.xenostudio.ai` | API plane | LLM routing, credits, pricing, usage, and the model catalog |\n\nSee [Files & local storage](/docs/hub/files-and-storage) for the full `~/.xeno/` layout.\n\n## Next steps\n\n- [Install XENO Hub](/docs/hub/installation)\n- [Quickstart](/docs/hub/quickstart) — sign in, launch an app, run the agent\n- [Signing in](/docs/hub/signing-in)\n\n> XENO Hub is proprietary software, © 2026 XENO Corporation. This documentation describes the shipping 0.11.x line and is reconciled against v0.11.18."
        },
        {
          "slug": "installation",
          "title": "Installation",
          "description": "Download XENO Hub for Windows, macOS, or Linux — or build from source.",
          "body": "## Installation\n\nDownload XENO Hub from the [Hub product page](/product/hub). The page and update feed expose only artifacts qualified for the current release; do not infer support for another platform from a source build script.\n\nOn Windows, run the published NSIS installer. Existing installations can update through Hub's update control. Finish active work before restarting.\n\n## Auto-updates\n\nHub checks the XENO update channel on startup and periodically while running. When a newer qualified build is available, the sidebar offers download progress and an explicit restart/install action. The installer feed is versioned; release notes remain available at the [Hub releases page](/product/hub/releases).\n\n## Building from source\n\nThe repository uses Electron, React, TypeScript, electron-vite, and electron-builder:\n\n```bash\nnpm install\nnpm run dev\nnpm run build:win\n```\n\nOther platform build commands are developer targets, not proof that a public artifact was certified. Optional Rust/N-API modules require Rust and xeno-lib; when they are absent, the related local features report unavailable rather than silently claiming success.\n\nNext: [Quickstart](/docs/hub/quickstart) · [Updates and releases](/docs/hub/updates)."
        },
        {
          "slug": "quickstart",
          "title": "Quickstart",
          "description": "Sign in, launch your first app, and run the agent.",
          "body": "## Quickstart\n\nOnce Hub is [installed](/docs/hub/installation), you are a few clicks from working.\n\n## 1. Sign in\n\nLaunch Hub and sign in with your XENO account — continue with Google, GitHub, or X, or use email and password. See [Signing in](/docs/hub/signing-in) for the full flow. On first run, an onboarding walkthrough introduces the main surfaces.\n\n## 2. Find your way around\n\nHub opens on the **Home** tab. A slim sidebar on the left switches between sections — Home, Store, Studio, Office, Corpo, Tools, Models, OS, Files, and System — and your account lives at the bottom. Press **Ctrl+K** any time to open the command palette and jump anywhere. See [The Hub interface](/docs/hub/interface) for the full tour.\n\n## 3. Launch an app\n\nOpen **Studio**, **Office**, or **Corpo** to see XENO's apps. Pick one (for example, Pixel) and install it — Hub downloads and installs it, showing live progress — then launch it. Hub tracks whether each app is running and offers update and uninstall controls. See [Apps & suites](/docs/hub/apps-and-suites).\n\n## 4. Run the agent\n\nOpen the **Agent** tab to chat with XENO's built-in AI agent. Ask it to do something in a workspace and it will use tools — reading and writing files, running commands, searching the web — asking your approval according to the active permission profile. See [The agent](/docs/hub/agent).\n\n## 5. Try a tool\n\nOpen **Tools** for standalone utilities: generate an image, upscale one, remove a background, convert a file, or capture your screen. See [Tools](/docs/hub/tools).\n\n## Next steps\n\n- [The Hub interface](/docs/hub/interface) — tabs, palette, shortcuts, and navigation\n- [Models](/docs/hub/models) — cloud and local\n- [Credits & billing](/docs/hub/credits-billing)"
        },
        {
          "slug": "signing-in",
          "title": "Signing in",
          "description": "Sign in with OAuth or email, and how your credentials and API key are stored.",
          "body": "## Signing in\n\nXENO Hub requires a XENO account. Signing in gives Hub two things: a **web token** (a JWT from `xenostudio.ai`) that identifies your account, and an **API key** (`xeno-…`) that is auto-provisioned for routing model calls through the XENO API.\n\n## Sign-in options\n\nFrom the login screen you can:\n\n- **Continue with Google, GitHub, or X** — Hub opens the provider's sign-in in your browser and returns to the app through the `xeno://auth/callback` deep link.\n- **Sign in with email and password** — handled directly against the platform auth API (`xenostudio.ai/api/auth`).\n- **Create an account** — register with a name, email, and password (minimum 6 characters).\n\nAfter a successful sign-in, Hub validates the token, loads your profile, and — if the server provides one — stores your API key.\n\n## Where credentials are stored\n\nCredentials live in `~/.xeno/credentials.json` as `{ webToken, apiKey }`. Hub restricts the file's permissions to your user account only (via `icacls` on Windows, `chmod 600` on macOS/Linux). Sign out at any time from **Account** to clear them.\n\n## The three backends\n\nOnce signed in, Hub talks to three planes:\n\n| Service | Base URL |\n|---------|----------|\n| Auth & platform APIs | `https://xenostudio.ai/api/` |\n| API plane (LLM, credits, models, pricing) | `https://api.xenostudio.ai/` |\n| Updates | `https://updates.xenostudio.ai/` |\n\nBilling and credits are always canonical on `api.xenostudio.ai` — never in local state. See [Credits & billing](/docs/hub/credits-billing).\n\n## Next steps\n\n- [The Hub interface](/docs/hub/interface)\n- [Credits & billing](/docs/hub/credits-billing)"
        }
      ]
    },
    {
      "title": "Using the Hub",
      "pages": [
        {
          "slug": "interface",
          "title": "The Hub interface",
          "description": "Tabs, the command palette, keyboard shortcuts, the navigation sidebar, tray, and deep links.",
          "body": "## The Hub interface\n\nHub is a tabbed workspace. A title bar across the top holds your open tabs; the active tab fills the window. Each major surface — the launcher, the agent, tools, and more — is its own tab, and tabs stay mounted in the background so switching between them is instant.\n\n## Tabs\n\nHub tabs come in a few types:\n\n- **Hub** — the launcher and its navigation sidebar (Home, Store, apps, Tools, Models, and so on).\n- **Agent** — the built-in AI agent. See [The agent](/docs/hub/agent).\n- **Code / IDE** — the agent's engineering workbench with a Monaco editor, diffs, and a terminal.\n- **Chat** — a lightweight conversational surface.\n- **Tool** — a standalone utility such as Image Gen or Capture. See [Tools](/docs/hub/tools).\n\n## The command palette\n\nPress **Ctrl+K** (or use the search control in the title bar) to open the command palette. It is the fastest way to jump to any section, open a tool, or navigate the app without reaching for the sidebar.\n\n## Keyboard shortcuts\n\n| Shortcut | Action |\n|----------|--------|\n| `Ctrl+K` | Toggle the command palette |\n| `Ctrl+1` … `Ctrl+9` | Switch to tab by position |\n| `Ctrl+W` | Close the current tab (unless pinned) |\n| `Ctrl+N` | Jump to the Agent tab |\n| `Ctrl+,` | Open account settings |\n| `Ctrl+B` | Toggle the sidebar |\n\nOn macOS, use Cmd in place of Ctrl.\n\n## The navigation sidebar\n\nInside the Hub tab, a slim icon rail on the left switches sections:\n\n| Section | What it is |\n|---------|-----------|\n| Home | Your dashboard, news, and quick entry points |\n| Store | The XENO Marketplace — see [Marketplace](/docs/hub/marketplace) |\n| Studio | Creative apps (Pixel, Motion, Sound, and more) |\n| Office | Productivity apps (Docs, Sheets, Slides, Notes) |\n| Corpo | Collaboration and communication apps |\n| Tools | The utility tools suite — see [Tools](/docs/hub/tools) |\n| Models | Cloud and local model catalog — see [Models](/docs/hub/models) |\n| OS | Isolated container environments (experimental) |\n| Files | A file manager over your XENO storage — see [Files & local storage](/docs/hub/files-and-storage) |\n| System | System health and diagnostics — see [Troubleshooting](/docs/hub/troubleshooting) |\n| Account | Your profile, credits, and settings |\n\n## System tray\n\nHub runs from the system tray for quick access even when the window is closed, and it registers global hotkeys for a few tools — for example, screen capture and voice-to-text can be triggered from anywhere. See [Tools](/docs/hub/tools).\n\n## Deep links\n\nHub registers the `xeno://` URL scheme, so links can drive the app:\n\n- `xeno://auth/callback` — completes an OAuth sign-in.\n- `xeno://app/<target>` or `xeno://navigate/<target>` — jump to a Hub section or app.\n\n## Next steps\n\n- [Apps & suites](/docs/hub/apps-and-suites)\n- [Marketplace](/docs/hub/marketplace)"
        },
        {
          "slug": "apps-and-suites",
          "title": "Apps & suites",
          "description": "Install, launch, update, and stop XENO's creative and productivity apps.",
          "body": "## Apps & suites\n\nHub is the launcher for every XENO app. Apps are grouped into three suites in the navigation sidebar:\n\n- **Studio** — creative apps (image, video, and audio editing and related creative tools).\n- **Office** — productivity apps: Docs, Sheets, Slides, and Notes.\n- **Corpo** — collaboration apps: unified email, messaging, calendar, and video conferencing.\n\nThe catalog is served from the platform and refreshed while Hub is open, so each card reflects what has actually shipped — apps still in development are marked accordingly, and each card links to its product page on `xenostudio.ai`.\n\n## Install, launch, and manage\n\nFrom an app card you can:\n\n- **Install** — Hub downloads and installs the app, streaming live progress through phases: *downloading → installing → complete* (or *error*). You can cancel an in-progress install.\n- **Launch** — start the app. Hub tracks running state, so a card reflects whether its app is currently open.\n- **Stop** — close a running app from Hub.\n- **Check for updates** — Hub knows each app's installed version and offers an update when a newer one is published.\n- **Uninstall** and **open install location** — manage the installed copy on disk.\n\nInstalled app versions are recorded in a local manifest under `~/.xeno/`, which is how Hub compares against the latest published version. See [Updates & releases](/docs/hub/updates) for how version detection works.\n\n## Send to XENO\n\nOn Windows, Hub adds a **Send to XENO** entry to the file context menu. Right-click an image, video, audio file, or a XENO project file (`.xpixel`, `.xmotion`) and Hub routes it to the right app. Hub also exposes direct bridges so tools can hand an image straight into a running Pixel or Motion instance.\n\n## Next steps\n\n- [Marketplace](/docs/hub/marketplace) — the broader catalog of apps, panels, plugins, models, and agents\n- [Updates & releases](/docs/hub/updates)"
        },
        {
          "slug": "marketplace",
          "title": "Marketplace",
          "description": "Browse and install apps, panels, plugins, MCP servers, models, and agents from the XENO Store.",
          "body": "## Marketplace\n\nThe **Store** section is the XENO Marketplace — one content-typed catalog for everything you can add to the ecosystem, with purchases and entitlements tied to your account. The catalog is served by the platform; the storefront lives inside Hub.\n\n## What you can install\n\nListings are typed by *kind*, so the same store carries very different things:\n\n| Kind | What it is |\n|------|-----------|\n| `app-native` | A full native XENO app installed to your machine |\n| `app-sandboxed` | A community app that runs inside a sandbox |\n| `panel` | A panel that plugs into a XENO app |\n| `plugin` | A plugin extending an app or the agent |\n| `mcp` | A Model Context Protocol server the agent can use |\n| `model` | A model you can install and run |\n| `mind` / `swarm` | A sellable agent — an authored Mind, or a coordinated swarm |\n\n## Browsing and buying\n\nYou can filter the catalog by kind, category, trust tier, and search text, and page through results. Opening a listing shows its detail page. Depending on the listing, you can acquire it for **free**, as a **one-time purchase**, on a **subscription**, as a **rental**, or **pay per use** — all metered against your XENO credits. Your **entitlements** — what you own or subscribe to — are resolved from your account, so an install you own on one machine is available on another after you sign in.\n\n## Installing and running\n\nInstalling a native listing streams the same *downloading → installing → complete* progress as the app suites, and you can launch native apps directly from the store. Sandboxed and metered listings run through the marketplace runtime. Before an install that requests sensitive capabilities, Hub shows a **capability consent** step so you can see and approve what it will be allowed to do.\n\n> The Marketplace is actively expanding across catalog, community publishing, agents, and metered payouts. What appears in your Store reflects what has been published to the live catalog for your account.\n\n## Next steps\n\n- [Apps & suites](/docs/hub/apps-and-suites)\n- [The agent](/docs/hub/agent) — agents you buy or rent run through the same agent surface"
        },
        {
          "slug": "files-and-storage",
          "title": "Files & local storage",
          "description": "The ~/.xeno directory, the Files manager, and backup and export.",
          "body": "## Files & local storage\n\nHub is local-first: your settings, workspaces, conversations, and caches live on your machine under the `~/.xeno/` directory, so they survive restarts and work offline. The platform is the canonical source for account, billing, and durable metadata, but Hub always keeps enough local state to keep going when the network is degraded.\n\n## The `~/.xeno/` directory\n\n| Path | Contents |\n|------|----------|\n| `credentials.json` | Your web token and API key (permissions restricted to your user) |\n| `settings.json` | Your preferences |\n| `workspaces.json` | Workspaces, teams, agents, and their settings |\n| `agent-chats/` | Persisted agent conversations |\n\nHub also keeps an installed-apps manifest and local image-project data here. User-facing state is never memory-only — conversations, workspaces, and settings are all persisted.\n\n## The Files manager\n\nThe **Files** section is a file manager over your XENO storage. From it you can browse roots and folders, open files (in Hub or externally), reveal them in your OS file explorer, rename and delete, and see disk usage. It is the quickest way to get to generated images, captures, transcripts, and exports.\n\n## Backup & export\n\nHub can package your local data so you can move it or keep a safe copy. From the relevant settings you can:\n\n- **Export** your data as JSON or CSV.\n- **Create, list, download, and delete backups**, and **import** a backup to restore.\n\nBecause everything lives under `~/.xeno/`, a backup is a portable snapshot of your Hub state.\n\n## Next steps\n\n- [The agent](/docs/hub/agent)\n- [Troubleshooting & FAQ](/docs/hub/troubleshooting)"
        }
      ]
    },
    {
      "title": "Agent & models",
      "pages": [
        {
          "slug": "agent",
          "title": "The agent",
          "description": "Hub's built-in AI agent — tools, permission profiles, workspaces, teams, and the engineering workbench.",
          "body": "## The agent\n\nHub mounts the canonical XENO Agent surface and Host runtime. It does not maintain a second chat implementation.\n\n## Chat and Agent\n\n**Chat** starts without asking for a project. The Host creates a private managed working directory for the provider process, but grants no authority over your repositories. **Agent** requires the exact local project root and enables workspace-aware files, commands, Git, review, terminal, and delegated work according to the active capability and permission policy.\n\nMode, workspace, provider binding, messages, runtime events, Goal/Loop/Handoff state, and nested-agent hierarchy persist with the session. Closing a tab does not delete its conversation.\n\n## Development workbench\n\nThe shared surface combines the conversation timeline with files, Monaco editing, terminals, repository/review state, checkpoints, diagnostics, permissions, and coordination. Tool calls render as typed compact records; expand one to inspect its arguments or result.\n\n## Providers and nested agents\n\nACP, SDK-native, and XENO Cloud lanes come from live Host descriptors. Unavailable, blocked, degraded, or approval-required states remain visible. Selecting a child agent opens its complete conversation and **Back to parent agent** returns to its parent without interrupting execution.\n\nRead the full [XENO Agent documentation](/docs/agent/introduction), [modes](/docs/agent/chat-and-agent-modes), and [Goal, Loop, and Handoff guide](/docs/agent/goal-loop-handoff)."
        },
        {
          "slug": "agent-runtime-updates",
          "title": "Agent modes, coordination, and independent updates",
          "description": "How Hub consumes the canonical XENO Agent surface and receives compatible interface releases without a new Hub installer.",
          "body": "## Agent modes, coordination, and independent updates\n\nHub mounts the canonical XENO Agent interface; it does not maintain a second chat or agent implementation. **Chat** starts immediately with a private Host-managed workspace and no project grant. **Agent** requires the exact local project folder and enables only the workspace-aware capabilities reported by the Host. Sessions preserve their mode and workspace when resumed.\n\nThe Agent surface projects durable Goal, Loop, Handoff, and nested-agent state from the Agent SDK. Goals require verification evidence, continuation/development loops are unbounded unless the user sets a limit, and live handoff transfers a fenced execution lease. Selecting a child opens its complete conversation; execution continues regardless of which agent is being viewed.\n\n## Independent interface delivery\n\nHub 0.11.18 contains a bundled recovery-floor surface and a verified loader for strictly newer signed packages declaring `agent@1`. Compatible renderer/interface updates can therefore ship through the Agent runtime registry without another Hub installer release.\n\nThe package receives only the existing request, event, and shell contract. New privileged preload methods, Electron-main behavior, native dependencies, trust-key changes, or breaking Host protocol revisions still require a full Hub release. Signature failure, an unsupported contract, handshake failure, or a render exception falls back to the bundled surface.\n\nFor the complete workflow, read the [XENO Agent documentation](/docs/agent/introduction), [Chat and Agent modes](/docs/agent/chat-and-agent-modes), and [Goal, Loop, and Handoff](/docs/agent/goal-loop-handoff)."
        },
        {
          "slug": "models",
          "title": "Models",
          "description": "Cloud models through the XENO API, and local models through the xeno-rt runtime.",
          "body": "## Models\n\nHub runs models two ways: in the **cloud** through the XENO API, and **locally** through the xeno-rt runtime. The **Models** section is where you browse both.\n\n## Cloud models\n\nCloud model discovery and inference belong to `api.xenostudio.ai`. Hub fetches a live model catalog, so the models available to you — and the default — stay current with your account without updating the app. Cloud runs are metered against your [credits](/docs/hub/credits-billing). Hub never silently substitutes a different model than the one you selected; if transport must fall back, the model stays the same.\n\n## Local models with xeno-rt\n\nFor private, offline inference, Hub runs models on your own machine through **xeno-rt**, the ecosystem's unified inference runtime. xeno-rt is the only supported local runtime.\n\nIn the Models section you can:\n\n- **Browse the local catalog** — installable models grouped by category: language, image, video, audio, upscale, and embedding.\n- **Install a model** — download a GGUF with live progress, verified against its expected identifiers.\n- **See what's installed** — Hub lists your actual local GGUFs with their size, parameter count, and family.\n- **Remove a model** — delete a local model to reclaim disk space.\n\nCategories that xeno-rt does not yet support locally are shown honestly as unavailable rather than hidden.\n\n## Runtime control\n\nHub manages the local runtime lifecycle for you — starting and stopping xeno-rt, warming a model before use, and running health checks so a model is ready when you send your first message. Local discovery is based on your local GGUF cache.\n\n## Next steps\n\n- [The agent](/docs/hub/agent)\n- [Credits & billing](/docs/hub/credits-billing)"
        },
        {
          "slug": "credits-billing",
          "title": "Credits & billing",
          "description": "View your balance and history, top up, and understand low-credit warnings.",
          "body": "## Credits & billing\n\nCloud AI in Hub — model calls, image generation, upscaling, and other API-backed features — is metered in **credits**. Credits are canonical on `api.xenostudio.ai`, never in local app state, so your balance is always authoritative.\n\n## Viewing your balance\n\nHub keeps your current balance visible and refreshes it as you work. From your **Account** you can review your **transaction history** and see usage broken down — for example, by model or by which agents consumed the most.\n\n## Low-credit warnings\n\nWhen your balance runs low, Hub raises a warning so you can top up before a run is interrupted. This keeps long agent tasks and batch generations from failing mid-way.\n\n## Topping up\n\nYou can purchase credits and manage your payment method from within Hub. Purchases are processed by the platform and reflected in your balance.\n\n## Local models don't cost credits\n\nInference you run locally through [xeno-rt](/docs/hub/models) does not consume credits — it runs entirely on your hardware. Credits apply to cloud model calls and API-backed tools.\n\n## Next steps\n\n- [Models](/docs/hub/models)\n- [The agent](/docs/hub/agent)"
        }
      ]
    },
    {
      "title": "Tools",
      "pages": [
        {
          "slug": "tools",
          "title": "Tools",
          "description": "Hub's built-in utility tools — image, media, document, and optimization helpers.",
          "body": "## Tools\n\nThe **Tools** section is a suite of standalone utilities that open as their own tabs. Each is focused on one job and works alongside the apps and the agent.\n\n## Image & AI tools\n\n| Tool | What it does |\n|------|--------------|\n| Image Gen | A standalone image-generation workspace with projects — see [Image generation](/docs/hub/image-generation) |\n| Upscaler | Upscale images through the XENO API pipeline |\n| Background Removal | Remove backgrounds from images with AI |\n| Resize | Resize and reposition images |\n| Asset Extractor | Extract individual assets from a source image |\n| UI Asset Extractor | Run UI extraction pipelines into modular asset folders with live per-asset progress |\n| Material Generator | Derive engine-ready PBR texture maps from images or prompts — see [Material Generator](/docs/hub/material-generator) |\n\n## Conversion & documents\n\n| Tool | What it does |\n|------|--------------|\n| Converter | Convert images and audio between formats |\n| Compressor | Compress files and images |\n| PDF Merge | Merge multiple PDFs into one document |\n| LaTeX Compiler | Edit and compile LaTeX documents to PDF |\n\n## Media capture\n\n| Tool | What it does |\n|------|--------------|\n| Capture | Screen capture, annotation, and sharing — available from a global hotkey |\n| Whisper | Voice-to-text transcription — toggle recording with a global hotkey |\n\nCapture and Whisper register system-wide hotkeys, so you can grab a screenshot or start dictating without switching to Hub first.\n\n## Local vs. cloud\n\nSome tools run locally and some go through the XENO API. Background Removal and Converter can use Hub's optional native modules for local processing; when those modules aren't installed, the tool falls back or is unavailable rather than failing silently. API-backed tools like Upscaler consume [credits](/docs/hub/credits-billing).\n\n> Two tools (Quick Share and Extractor) appear in the Tools grid marked *coming soon* and are not yet available.\n\n## Next steps\n\n- [Image generation](/docs/hub/image-generation)\n- [Material Generator](/docs/hub/material-generator)"
        },
        {
          "slug": "image-generation",
          "title": "Image generation",
          "description": "Generate images in projects, attach references, and use slash commands for precise edits.",
          "body": "## Image generation\n\nThe **Image Gen** tool is a full image-generation workspace. Work is organized into **projects** that persist locally, so your generations, prompts, and settings survive restarts. You can create projects, set a preferred model per project, favorite results, and browse large galleries with cached previews that fill the grid instantly while fresh generations stream in.\n\n## Generating\n\nEnter a prompt, optionally attach one or more **reference images**, choose your model and parameters, and generate. You can send images into Image Gen from other surfaces — for example from Files or the UI Asset Extractor — and Hub attaches them as pending references in the Default Image Gen project.\n\n## Slash commands\n\nInside the prompt you can type `/` to bring up a command bar of edit operations. Selecting one turns it into an inline pill; on send, Hub expands the pill into a full, carefully-worded instruction to the model (hover a pill to see exactly what will be sent). Available commands include:\n\n| Command | Purpose |\n|---------|---------|\n| `/extract` | Extract a UI card or container on a green screen |\n| `/extract-only` | Pixel-faithful extraction of named elements on solid green |\n| `/remove` | Remove named elements while preserving the host exactly |\n| `/remove-bg` | Cut the subject out on a transparent background |\n| `/retexture` | Change the material while preserving shape and lighting |\n| `/style` | Re-render the same content in a different visual style |\n| `/colorize` | Recolor only, preserving lighting and value structure |\n| `/relight` | Change lighting while preserving content and materials |\n| `/isolate` | Place the subject on a flat studio background |\n| `/quality-increase` | Increase quality, preserve texture, and clean up artifacts |\n\nThese make precise, repeatable edits far easier than hand-writing the same long instructions every time. The `/quality-increase` command was added in v0.5.1.\n\n## Next steps\n\n- [Tools](/docs/hub/tools)\n- [Material Generator](/docs/hub/material-generator)\n- [Credits & billing](/docs/hub/credits-billing)"
        },
        {
          "slug": "material-generator",
          "title": "Material Generator",
          "description": "Turn images or prompts into engine-ready PBR material packages with a 3D preview and Unreal import.",
          "body": "## Material Generator\n\nThe **Material Generator** turns a source image or a text prompt into a complete, engine-ready PBR material package — with a live 3D preview and a direct path into Unreal Engine. It was the headline of the v0.5.1 release.\n\n## Two ways to start\n\n- **Source mode** — upload a PNG, JPEG, WebP, or BMP image and choose the material type, style, and which maps to output.\n- **Generate mode** — enter a texture prompt and optionally attach a reference image, then generate the material from the result.\n\nHub produces the standard PBR map set — base color, normal, height, roughness, ambient occlusion, metallic, and emissive — for whichever outputs you enable.\n\n## 3D preview\n\nA real-time 3D viewer renders the material on a sphere, not just as flat map thumbnails, so you see normal, roughness, metallic, and emissive response together. You can orbit, zoom, and pan, and move the lighting to inspect the material under different conditions.\n\n## Exporting a package\n\nExport writes a self-contained package: the map PNGs plus a manifest and readme. When you choose Unreal as a target, Hub also writes the import files Unreal needs.\n\n## Unreal import\n\nIn the import panel you can point Hub at your Unreal projects. After discovery, selecting a project and importing copies the raw package under the project's `Saved/XENO` folder and — when Unreal's Python remote execution is available — creates textures and materials under `/Game/XENO/Materials/<material-name>/`. Hub generates both a base material (`M_<name>`) and a material instance (`MI_<name>`) exposing artist-safe parameters such as tint, emissive tint, saturation, contrast, roughness and metallic strength, AO intensity, height and normal strength, and UV tiling and offset. Helper files stay under `Saved`; only real Unreal assets go into `Content`.\n\n## Next steps\n\n- [Tools](/docs/hub/tools)\n- [Image generation](/docs/hub/image-generation)"
        }
      ]
    },
    {
      "title": "Reference & help",
      "pages": [
        {
          "slug": "updates",
          "title": "Updates & releases",
          "description": "How Hub updates itself and the apps it manages.",
          "body": "## Updates and releases\n\nHub manages two independent update classes.\n\n## Hub application updates\n\nHub checks its versioned desktop feed on startup and periodically. When an update qualified for your platform is available, the sidebar offers an explicit download and restart/install flow. Active work is not restarted automatically.\n\n## Installed product updates\n\nFor products delivered as desktop applications, Hub reads their versioned release feeds and compares them with the installed-app manifest under `~/.xeno/`. Each product keeps its own release history and qualification boundary.\n\n## Signed runtime packages\n\nSome compatible surfaces and tools use the signed component registry rather than a whole Hub installer. Hub 0.11.18 introduces the verified `agent@1` loader: a strictly newer Agent renderer can replace the bundled recovery floor while privileged Electron-main and Host protocol changes still require Hub.\n\n## Recovery\n\nIf verification, download, contract negotiation, or rendering fails, Hub keeps the last trusted or bundled surface. Do not delete local session data to force an update. Inspect [Troubleshooting](/docs/hub/troubleshooting) and the [Hub release history](/product/hub/releases)."
        },
        {
          "slug": "troubleshooting",
          "title": "Troubleshooting & FAQ",
          "description": "System health, support bundles and repairs, and answers to common questions.",
          "body": "## Troubleshooting & FAQ\n\n## System health\n\nThe **System** section reports on Hub's health — the state of local runtimes, storage, and connectivity — so you can see at a glance whether something is wrong before it bites.\n\n## Support tools\n\nWhen you do hit a problem, Hub can help you diagnose and recover:\n\n- **Create a support bundle** — package diagnostics into a shareable report.\n- **Repair** — run Hub's self-repair to fix common local-state issues.\n- **Run migrations** — bring local storage up to date after an update.\n- **Profile** — capture performance information.\n\nHub also keeps a crash log you can review and clear, and reports errors so they can be fixed.\n\n## Common questions\n\n**A local feature (background removal or conversion) is unavailable.** Those rely on optional native modules that aren't built in every install. Hub degrades gracefully when they're missing — see [Installation](/docs/hub/installation) for building the native modules locally.\n\n**The agent won't touch a file or run a command.** Check the active [permission profile](/docs/hub/agent) and the directories you've allowed. Read-only and plan profiles won't make changes, and anything outside your allowed directories prompts for access.\n\n**My credit balance looks wrong.** Credits are canonical on the API plane, not local state. Refresh from your [account](/docs/hub/credits-billing); local numbers are only a cached view.\n\n**I want to work offline.** Sign in once, then use local [models](/docs/hub/models) through xeno-rt and the local tools. Your conversations, workspaces, and settings live under `~/.xeno/` and survive restarts and network outages.\n\n**Hub says an update is available but I'm mid-task.** Updates only install when you click through the download and restart — finish your work first, then apply it. See [Updates & releases](/docs/hub/updates).\n\n**Where is my data?** Everything local lives under `~/.xeno/`. See [Files & local storage](/docs/hub/files-and-storage), where you can also back it up and export it.\n\n## Next steps\n\n- [Files & local storage](/docs/hub/files-and-storage)\n- [Updates & releases](/docs/hub/updates)"
        }
      ]
    }
  ]
};

export default hub;
